### ISSUE TITLE
Build Started but no build started on Jenkins

### ISSUE THREAD

**Issue by carterdanko** [KyleLNicholls/parameterized-builds#102]
Setup the hook along with the project jenkins settings, on manual the pop-up shows "Build Started" but nothing is started on the jenkins instance.  On push events/ref created/PR opened nothing happens at all.

Running on Bitbucket 5.4.0 and tried 2 different Jenkins instances, one with HTTPS turned on and another turned off.  HTTPS Jenkins version is 2.19.1 and HTTP is 2.15.

@a-hacker Helped starting investigate the issue but could not find the root cause of the issue.

**Comment by a-hacker** [comment]
I've talked with @carterdanko about this and it appears to be a network error on their end.
