### ISSUE TITLE
How to trigger a parameterized Jenkins Job

### ISSUE THREAD

**Issue by rockjing** [KyleLNicholls/parameterized-builds#106]
I could define a webhook in one repository and manually trigger it through  Build in Jenkins in action of branch.
One IT guy wants to trigger it after PR megered, and send 2 parameters (PR user and PR description) to Jenkins. Once Jenkins job built successfully or failed then  the jenkins could send an email to the PR user.

I tried to define PRUSER in configuration page of webhook page of Bitbucket, but after click build in jenkins in one branch's action button. It fired an errror  - **Error triggering job, invalid build parameters**.
In one word, I don't know how to config it to send parameters to Jenkins.

Software version:
Jenkins: 2.7.1
bitbucket: v4.12.1

Can someone give some advice? Thanks.

**Comment by rockjing** [comment]
I found the jenkins job should be configed as build with parameters. So the plugin of bitbucket could trigger it normally.

**Comment by a-hacker** [comment]
Hi @rockjing. You will have to make sure that the parameters you specify in the configuration match the parameters on the jenkins job itself. Are you still having this issue or did you get it figured out?

**Comment by a-hacker** [comment]
It sounds to me like you resolved your problem @rockjing so I'm going to close this issue. If you still require assistance, please re-open this issue.
