### ISSUE TITLE
Manual trigger for multibranch feature branches not working

### ISSUE THREAD

**Issue by bhoppeadoy** [KyleLNicholls/parameterized-builds#107]
Hi, I'm running 

BitBucket Server v5.4.1 
Parameterized-builds 3.2.0 
Jenkins 2.93 and latest version of all other Jenkins plugins.  

I have a multibranch pipeline setup in Jenkins. I have the parameterized build hook setup for REF_CREATED, REF_DELETED, PUSH_EVENT and MANUAL and the 'Multibranch Pipeline' checkbox checked.  Except for MANUAL, these events work fine for both develop branch and feature branches. My feature branches would be named something like 'feature/WBQA-432-some-feature-title' or 'bugfix/WBQA-223-some-bug'

The MANUAL trigger does work for the develop branch from BitBuckect. The feature branches do not work for MANUAL trigger. When I start the build manually, a green popup appears with "Build started". Then after a few moments a yellow popup appears with "Job was not found". 

I suspect this has something to do with the forward slash in the feature branch name.

**Comment by bhoppeadoy** [comment]
I'm not sure if PR#108 solves this for Pull Requests as well but I'm having the same issue with manual build from a Pull Request. 

I'm using BitBucket Branch Source as the repository for my multibranch pipeline. The job path for the feature branch is as such:
/job/my-project/job/feature%2FWBQA-432-some-feature-title/

The job path for the pull request shows as:
/job/my-project/view/change-requests/job/PR-13/

Different since there isn't a reference to the branch name. What job path are you expecting for PR?

**Comment by a-hacker** [comment]
@bhoppeadoy, #108 should fix the issue in general but won't in your case.

Jenkins multibranch pipelines can be configured to create subjobs for PRs that are distinct from the branch subjobs. From what you've told me, it sounds like your multibranch pipeline is configured this way. Unfortunately, this plugin does not support that workflow yet. Instead, a PR trigger will build the pipeline subjob associated with the branch the PR was made from.

I understand that this may not work with your workflow and I would like to look into making this plugin more flexible with respect to multibranch pipelines but that will have to be a new feature request. I'd ask that you please open a new issue for this request.
