### ISSUE TITLE
Add new variables-replacements to Build Parameters

### ISSUE THREAD

**Issue by uweschaefer** [KyleLNicholls/parameterized-builds#11]
We could use some more Variables in Build Parameters, like the repository path (Project/Repository). If this is considered a reasonable addition, i'd work on that and issue another PullReq.

What comes to mind:

$REPO_PATH
$REPO_NAME
$PROJECT_NAME

but we're open to other ideas.

**Comment by uweschaefer** [comment]
Settled for only 

$REPOSITORY and
$PROJECT

Let me know, what i forgot :)

**Comment by KyleLNicholls** [comment]
lgtm, thanks!
