### ISSUE TITLE
"Error triggering job, invalid build parameters" on jenkins

### ISSUE THREAD

**Issue by cstmgl** [KyleLNicholls/parameterized-builds#111]
hi All,

I'm very new to this, and I'm just trying to understand how to properly use this.

What I want is to just have a simple hook in bit-bucket that in each new push to the repository executes a certain jenkins job.

so this is my job

![image](https://user-images.githubusercontent.com/33542778/34599738-da5b51e6-f22e-11e7-97b3-213b15eb8f8f.png)

This is my hook details:

![image](https://user-images.githubusercontent.com/33542778/34599837-5f808e40-f22f-11e7-970e-df5f9d0b54f6.png)

I have a few questions but I think the cause is the same.
If I execute a push nothing seems to happen, probably because the failure.
If I execute manually I get the error message.
I checked the code and it seems to be related to getting an http status 500 in the response.

After reading https://github.com/KyleLNicholls/parameterized-builds#build-parameters
I have a few questions:
I've tried several versions of the parameters but I always get this error so:

- are the parameters in jenkins case sensitive?
- do I need to specify all of them?
- by some reason even though I define one of the boolean as true when I use it the checkbox always comes untick
![image](https://user-images.githubusercontent.com/33542778/34600010-65eeb198-f230-11e7-9b7a-b63c5b8ba62a.png)

This is the result after I execute it:
![image](https://user-images.githubusercontent.com/33542778/34600108-c86d0df6-f230-11e7-932d-7845ce114f6b.png)

I'm not sure where is the best place to ask this questions I was looking for some kind of community forum but I think here might not be bad in case someone has the same questions as me in a future. 
Even though I'm pretty sure there is no bug here.

**Comment by a-hacker** [comment]
Hi @cstmgl, this is definitely the best place to ask your questions.

1. **are the parameters in jenkins case sensitive?** Yes. Jenkins requires case-sensitive parameters in the rest call to trigger a job. This is how this plugin runs jenkins jobs.

2. **do I need to specify all of them?** No. Any that you do not specify will use the default value you've specified in your jenkins job.

3. **by some reason even though I define one of the boolean as true when I use it the checkbox always comes untick** I noticed that awhile back too and haven't gotten around to fixing it. Automated triggers will still use a value of true. It's just an issue with the manual trigger.

As for the issue that you have, you are correct that the message you see is related to a 500 status code. This is often caused when a value being passed in is not a valid choice in a jenkins choice param. It looks like you might be having that issue with `VERSION_TO_BUMP` or possibly `PROJECT` or `REPOSITORY`.

Let me know if this helps you solve your issue!

**Comment by cstmgl** [comment]
I think I found the problem and it was in a choice parameter but not the one I was thinking.
thank you for the feedback and you can close this now.

the parameter that was wrong was the project that was always upper case but in some of my options it can be lowercase.
