### ISSUE TITLE
Parameterized Builds + Commit Graphs causing problem

### ISSUE THREAD

**Issue by wysockip** [KyleLNicholls/parameterized-builds#113]
Hi,

When you have Parametrized Build and Commit Graphs plugins (https://marketplace.atlassian.com/plugins/com.plugin.commitgraph.commitgraph/server/overview) installed in the same time and the repository name contains world "jenkins" when you click on the "Network" tab (comming from Commit Graphs plugin), it's redirecting into the Admin Jenkins Settings instead of showing "Network" Tab from Commit Graphs. 

Seems in this special circumstances Parametrized Build plugin "Commit Graphs" plugin not working correctly. Any chance if someone could take a look on that?

Best regards
Pawel

**Comment by a-hacker** [comment]
Hi @wysockip. Thanks for submitting this issue. It's very similar to my first issue: #48!

I just went ahead and installed the Commit Graph plugin you mentioned, set up a repo to be names `jenkins` and everything worked as expected. Do you know what version of our plugin you are using? If it is older than 2.6.2, you'll need to update. If not, I'll need some more information to be able to reproduce this problem.

**Comment by wysockip** [comment]
Hi,
Thanks for answer.
Bitbucket version: 4.11.2
Parameterized Builds for Jenkins: 2.6.1
Commit Graph: 2.1

We will try with the 2.6.10 which is the one compatible with our Bitbucket.

Best regards
Pawel

**Comment by a-hacker** [comment]
Glad I could help. I'm going to close this issue but if you still are experiencing issues after upgrading, please re-open it or comment and I'll investigate further.
