### ISSUE TITLE
Project "Jenkins Settings" can't be configured using the REST API

### ISSUE THREAD

**Issue by nomis** [KyleLNicholls/parameterized-builds#117]
There needs to be a REST API to configure the "Jenkins Settings" at the project level.

It's time consuming and error prone to have to configure this for each project manually, when the REST API should allow configuration to be automated.

**Comment by a-hacker** [comment]
Hi @nomis. Thanks for adding this request. I know other users would like to see a better REST API supported for this plugin for exactly the reasons you mentioned. I just created a project to triage possible endpoints that we can support. Currently, yours is the only issue there but I plan on adding more this weekend.

My biggest concern about this type of POST endpoint is security. Only project admins should be able to post to this type of endpoint. Any PR adding this feature should involve tests checking that users with different levels of permissions can or cannot successfully post a configuration.

**Comment by a-hacker** [comment]
Project Settings can now be updated from the REST API as of version 4.0.3. Documentation is provided as a [swagger spec](https://github.com/KyleLNicholls/parameterized-builds/blob/master/src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/spec.yml)
