### ISSUE TITLE
Support for forking workflow when triggering builds from pull requests

### ISSUE THREAD

**Issue by bootFyre17** [KyleLNicholls/parameterized-builds#119]
My organization is looking for ways to trigger Jenkins builds from pull requests that come from repository forks. We use this plugin today and am hoping that there may be support for a fork based workflow either existing or in-flight. I am unable to get a build to trigger from a pull-request from a forked repo as it stands today.

**Comment by a-hacker** [comment]
Version 3.2.4 has been released with this fix
