### ISSUE TITLE
Trigger a build on a PR Approval?

### ISSUE THREAD

**Issue by benze** [KyleLNicholls/parameterized-builds#123]
I see there are options to trigger on PR Merged, PR Declined, PR Deleted.  Is there a particular reason why there isn't an option to trigger on PR Approved?  

I have a workflow where the PR gets approved, but the PR doesn't get merged until a later date.  I'd like to build on PR approval.   Is that feasible?  My workaround now is to trigger a build on a PR-open, but that may mean several builds until it gets approved.

Thanks,

Eric

**Comment by a-hacker** [comment]
Hi Eric. There is no particular reason why the plugin lacks a PR Approved trigger. It should be easy enough to add that in. Chances are the trigger would occur whenever an approval occurs and not just the first approval. Would that work for you?

**Comment by a-hacker** [comment]
Version 3.2.4 has been released with this enhancement.
