### ISSUE TITLE
Need to redirect link for "Get Jenkin API Token" under Jenkins setting ( for parameterized builds )

### ISSUE THREAD

**Issue by lazyyogi1** [KyleLNicholls/parameterized-builds#131]
Hi Team,

We are also facing an issue expalined below, so could you have a look and provide input on below issue.

Clicking on "Get Jenkin API Token" under Jenkins setting, it get redirecting to different jenkins link.

Issue Description:

In Bitucket, when I tried to configure API token to integrate with Jenkins users going through setting "Manage Account --> Jenkins Settings --> Jenkins User Setting --> Token --> then click on "Get Jenkins API Token" button"

resultant: It get redirected to different jenkin Url "https://abc.example.com/jenkins/user/dushyant.kumar_example.com/configure"

But in my jenkins setup, we are login with Userid without domain(example: dushyant.kumar  instead of dushyant.kumar@example.com), which is alos configured with LDAP.

Below is the redirect link which we are look as (Without "_example.com"):
"https://abc.example.com/jenkins/user/dushyant.kumar/configure" 

Note:
current link configured (User slug) as :- "dushyant.kumar_example.com"
![jenkins_integrate_error1](https://user-images.githubusercontent.com/28559292/39263173-f37d4944-48b0-11e8-9d59-d2863513db2f.JPG)

Required link as which need to configure (user slug) as :- "dushyant.kumar"
![jenkins_integrate_required1](https://user-images.githubusercontent.com/28559292/39263187-fc3b74e8-48b0-11e8-8804-3732a2250dfe.png)

Really appreciate if could you please help me to resolve this issue, ( Suggest how we can manipulate with link).

**Comment by a-hacker** [comment]
Hi @lazyyogi1. You may actually be interested in #49. Although that was originally opened concerning manual triggers, the core problem with that issue is that a user's Jenkins username is not the same as the Bitbucket username. This also appears to be causing your issue and even if that link worked for you, I do not believe that setting your jenkins API token will successfully trigger a build since it will use an invalid username. If I'm wrong about that, please correct me. Otherwise, I'd recommend that you give that issue a :+1: and close this one.

**Comment by lazyyogi1** [comment]
Hi a-hacker,

I doubt because It was working with my previous installed version. or Is there any way to redirect the url to connect with Jenkins to generate API token.

In #49 bug:

I don't understand about below points:

What I am asking is one of the following:
•To be able to provide in the Settings the Jenkins username to use in the authentication (default blank)
 Or
•Provide $USERID as part of the Manual trigger so Jenkins job could access the user info using REST API and will know who triggered the Manual build.

Could you please elaborate more on this.

**Comment by a-hacker** [comment]
I'm closing this issue as it has not had any activity in several months. If it should remain open, please re-open with a justification.
