### ISSUE TITLE
error with new version while updating jenkins token

### ISSUE THREAD

**Issue by parthshah705** [KyleLNicholls/parameterized-builds#137]
I'm receiving an error when I enter Jenkins token and hit 'SAVE' button.

"POST /plugins/servlet/jenkins/account HTTP/1.0" c.k.s.p.ciserver.CIServlet Exception in CIServlet.doPost: null

**Comment by a-hacker** [comment]
Hi @parthshah705, thanks for reporting this issue. However, the issue was already reported in issue #130. Luckily there is already a PR up with a fix so hopefully it will be released soon!
