### ISSUE TITLE
Option to reject a pull request if tests fail

### ISSUE THREAD

**Issue by FlashSheridan** [KyleLNicholls/parameterized-builds#151]
I would like an option to have a pull request be rejected if the triggered Jenkins build fails its test(s) (or any post-build action, for that matter).  I found this extremely helpful with GitHub pull requests where a developer frequently broke unit tests.  It would also be useful for enforcing coding standards or avoiding static analysis problems.

**Comment by a-hacker** [comment]
Hi @FlashSheridan. Thank you for your suggestion.

I believe this is out of scope of this plugin. Parameterized Builds for Jenkins is only responsible for triggering Jenkins jobs. Once the trigger happens, it has no concept of build status or tracking. You may want to look into using the [Stash Notifier plugin](https://plugins.jenkins.io/stashNotifier) or [Bitbucket Build Status Notifier plugin](https://plugins.jenkins.io/bitbucket-build-status-notifier) for Jenkins to report statuses back to Bitbucket. 

If you do that, you can configure pull requests to require a passing build in the repository or project settings. To do so, enable `Minimum Successful Builds` in the Merge Checks tab. I hope this is helpful!
