### ISSUE TITLE
Is there a way to trigger a build on destination branch instead of source branch

### ISSUE THREAD

**Issue by eawasthi** [KyleLNicholls/parameterized-builds#152]
Issues usually fall in one of three categories: questions, bugs, or enhancement requests

###Questions

Questions should be directed to our [Gitter](https://gitter.im/parameterized-builds/Lobby) first.

###Bugs
Is there a way to trigger a build on destination branch instead of source branch
Bug reports should include the following information:

- _Parameterized Builds for Jenkins_ plugin version
- _Bitbucket_ version
- _Jenkins_ Version
- Any _Jenkins_ or _Bitbucket_ settings that could be relevant
- Detailed description of the issue

In general, make the report actionable. An issue that only says "Pull request triggers do not work" does not provide
enough information to act on. However, an issue that says "Jenkins jobs located within folders cause a 'Job not found'
pop-up on Bitbucket 5.4.0, plug-in version 3.2.4, and Jenkins 2.70" is much easier to investigate.

Bugs that do not provide enough information may be closed with the "can't reproduce" label.

###Enhancement Requests

Enhancement requests are highly encouraged and should follow these guidelines:

- Use the requested feature name as the title of the issue.
- Include a description of what the feature is and the expected behaviour.
- Propose a use-case for the feature to provide context on why the feature is beneficial.

**Comment by a-hacker** [comment]
Hi @eawasthi, could you please update the description with some details about what you are trying to accomplish?

If I assume you are using a regular style job, then you should be able to pass $PRDESTINATION into a parameter for the job. That will give you the destination branch name which you can pull instead.

Does this solve your issue?

**Comment by a-hacker** [comment]
@eawasthi I'm going to close this issue. If my previous comment does not work for you, please re-open the issue with more details.
