### ISSUE TITLE
New Bitbucket tag to trigger Jenkins job Question

### ISSUE THREAD

**Issue by klymsoftware** [KyleLNicholls/parameterized-builds#153]
I already have Bitbucket and jenkins configured for push's, and pull requests . However now i'd like to trigger a new jenkins job when a new tag is created. In Bitbucket, when I set the ref type to tag, trigger to ref created, then create a new tag in Bitbucket, the build does not start in Jenkins. 

This appears to be a common issue.

Is there now a way to trigger a Jenkins build anytime a tag is created AND pass that tag as a parameter to Jenkins?

**Comment by a-hacker** [comment]
Hello @klymsoftware. I just tested this on the latest version of the plugin (3.2.6) and Bitbucket Server 5.4.0. Creating a ref triggered a jenkins job as expected. I will need more information about your set-up to assist further. Please see the [the issue template](https://github.com/KyleLNicholls/parameterized-builds/blob/master/.github/ISSUE_TEMPLATE.md) about what to include.

Also, why do you say this is a common issue? I have not seen this come up as an issue here or a question on either stackoverflow or the atlassian forums. I ask out of genuine curiosity as it may provide the details I need to get to the root of this issue.

**Comment by klymsoftware** [comment]
@a-hacker thank you for the quick reply, ill try to go into more detail.

Jenkins ver. 2.107.2
Atlassian Bitbucket v5.3.0
I don't have permissions to view the plugin version.

I'm trying to communicate between Bitbuckets "Parameterized Build for Jenkins" plugin and my Jenkins job. All i require is for any tag created to trigger the job, and pass the tag name as a Parameter to Jenkins.

![debug](https://user-images.githubusercontent.com/43445669/46353055-4053e980-c629-11e8-8bbb-40abd6a6f001.png)

My Bitbucket account also has the Jenkins API token set. The plugin is working because my other Parameterized Build starts a Jenkins build on a new pull request.

![debug2](https://user-images.githubusercontent.com/43445669/46353605-a12ff180-c62a-11e8-9879-510a9e6a63d0.png)

Im guessing when the event occurs the TAG parameter will be included in the branch name. Or will there be a separate ${TAG} parameter I can use?

![debug3](https://user-images.githubusercontent.com/43445669/46353894-41861600-c62b-11e8-95f3-c918679aff0b.png)

Once I create the tag nothing happens on Jenkins.

I called it a common issue because other people online have had trouble getting this to work using Bitbucket's post-webhook with Jenkins Git plugin. I didn't mean it was i common issue using this plugin.

Any help is really appreciated.

**Comment by a-hacker** [comment]
I just tested against bitbucket version 5.3.0 using the same settings that you've posted and I was still able to successfully trigger a build. To verify, here are screenshots of what I did.

Trigger Settings:
![image](https://user-images.githubusercontent.com/3665996/46356256-603adb80-c630-11e8-8856-ed0536ac23dd.png)

Jenkins Job Token:
![image](https://user-images.githubusercontent.com/3665996/46356366-98dab500-c630-11e8-8072-22534a58cb84.png)

Tag Name:
![image](https://user-images.githubusercontent.com/3665996/46356398-ac861b80-c630-11e8-851a-5f8ceb6415c2.png)

Successful Jenkins Build:
![image](https://user-images.githubusercontent.com/3665996/46356557-fc64e280-c630-11e8-812c-6f644843e744.png)

I don't recall any previous issues with tags not triggering builds but you might want to ask your local bitbucket admin to update the plugin to the latest version. You could also try setting the manual trigger type and seeing if a manual build goes through.

**Comment by a-hacker** [comment]
Also, to answer your question about getting the tag name, you will want to use the $BRANCH variable.

**Comment by klymsoftware** [comment]
Are you creating your tag from a Git command line or right from Bitbucket? Also even after I enable manual triggers I am unable to select manual build from Bitbucket, as the option is not available.  

![tag](https://user-images.githubusercontent.com/43445669/46369405-e1a26600-c650-11e8-93b2-60e6da05bd68.png)

**Comment by a-hacker** [comment]
Sorry for the delay. There is no manual build button for tags, only branches. I didn't even realize that, sorry. I would still try a manual build of a branch though. There could be something else wrong with your job that is unrelated to the tag.

**Comment by klymsoftware** [comment]
my Bitbucket project doesn't have a default user and token, I only have the Jenkins API token set for my account. Could this be the cause of my issue?

**Comment by klymsoftware** [comment]
This issue has been solved. It seems like just having an account API token is not enough. This build on new tag functionality requires a default user and default token to be set.

**Comment by a-hacker** [comment]
Having an account API token should be enough as long as your user has permissions to build the jenkins job you are trying to trigger. I just tested it and I did not need the default user and token to be set to trigger a build from a tag creation. At the very least, it is good that you got your job working. I'm going to close this issue but if you think something is still amiss, please re-open.
