### ISSUE TITLE
Add manual build button for tags

### ISSUE THREAD

**Issue by a-hacker** [KyleLNicholls/parameterized-builds#154]
The branch view in Bitbucket only allows manual builds for branches. It should also allow manual builds for tags.

Branch options:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/3665996/46554557-b4eb8a00-c8ae-11e8-8a1f-503d2d04f592.png">

Tag options:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/3665996/46554594-caf94a80-c8ae-11e8-8db2-bca7ed7d08c0.png">

**Comment by mishahliba** [comment]
taking issue

**Comment by a-hacker** [comment]
Fixed by #156. Thanks again @mishahliba
