### ISSUE TITLE
BUG: Using TAG as ref type, does not gie you a "Build in Jenkins Button"

### ISSUE THREAD

**Issue by mechatheo** [KyleLNicholls/parameterized-builds#161]
Parametrized Builds Version: 3.2.5
Bitbucket Version:  v5.13.0
Jenkins: 2.147

 In my repository i've set up triggers for branch an tag refs. Everything works fine for Branch refs, in particular i can click on build in jenkins, as shown in the following picture

![image](https://user-images.githubusercontent.com/20418799/47545645-a3196780-d8ed-11e8-950a-90445fd58530.png)

However when i configure the hook to use tags as ref type, there is no such button, as shown below:

![image](https://user-images.githubusercontent.com/20418799/47545652-add3fc80-d8ed-11e8-8d45-31e3813cff67.png)

Is this expected? Of course i can go to the commit and click "Build in Jenkins" from there, however finding Tags is much more convinient in Bitbucket.

**Comment by a-hacker** [comment]
Hi @mechatheo. This feature was just released in [3.2.7](https://github.com/KyleLNicholls/parameterized-builds/releases/tag/3.2.7) a few days ago. If you update the plugin to the latest version, you should see the manual build button for tags.
