### ISSUE TITLE
PR MERGE does not trigger Jenkins job when PR is merged remotely

### ISSUE THREAD

**Issue by syryin** [KyleLNicholls/parameterized-builds#166]
### Bug

3.2.6 - _Parameterized Builds for Jenkins_ plugin version
5.10.0 - _Bitbucket_ version 
2.153 - _Jenkins_ Version

Triggers enabled for this Hook: "PR MERGED", "AUTO MERGED"

- Detailed description of the issue

When the pull request are merged by clicking the button "Merge", the hook works. It triggers the remote Jenkins job.
When there is a merge conflict and the developer merge the pull request in IDE then the hook does not work. The PR is merged saying "remotely merge", but it does not trigger Jenkins job.

This fix will help in auto build and deployment, rather than manual build each time when there is conflict

Thanks

**Comment by a-hacker** [comment]
Hi @syryin,

Thanks you for reporting this bug! I just created a PR with a fix and will release a new version of the plugin once it is merged.

**Comment by syryin** [comment]
Thanks a lot

**Comment by a-hacker** [comment]
Fix released in 3.2.10
