### ISSUE TITLE
Add EULA

### ISSUE THREAD

**Issue by KyleLNicholls** [KyleLNicholls/parameterized-builds#182]
It is important to us that you provide User Terms, but more importantly, this is a vital requirement for your users to have the rights they need to use your apps. Whether your apps are hosted via server, data center, or the cloud, we require an End User License Agreement (for server and data center apps) or User Terms (for cloud apps) be added to the latest version of your apps.

Why this is required and what to include in your User Terms
By removing the "Standard EULA Terms" from our new Marketplace Agreements that will take effect on March 31st, we are recognizing that vendors have multiple app deployment options (server, cloud, and data center), and are giving vendors the ability and responsibility to set their own terms with users. While Atlassian cannot provide you with legal advice as to the content of your EULA or cloud Terms of Use, such agreements typically include, but are not limited to, clauses such as, (1) License Rights and Restrictions (in the case of a EULA);(2) Use Rights and Restrictions (in the case of SaaS); (3) Limitations of Liability; (4) Indemnification; (5) Warranties; (6) The parties' Termination Rights; (7) Support, and (8) Service Levels (for SaaS).
Apps that do not have a Vendor provided EULA or Terms of Use (as applicable) will be delisted from the Atlassian Marketplace after March 31st when the new Atlassian Vendor Agreement takes effect.

**Comment by a-hacker** [comment]
EULA link added on marketplace.
