### ISSUE TITLE
v4.0.0 - Unable to render configuration form for Parameterized Builds for Jenkins

### ISSUE THREAD

**Issue by krm1** [KyleLNicholls/parameterized-builds#183]
### Bugs
- **Parameterized Builds for Jenkins_ plugin version:** 4.0.0
- **Bitbucket_ version:** 6.0.0
- **Jenkins_ Version:** not relevant
- **Detailed description of the issue:**
On Bitbucket Server 6.0.0 when trying to activate a hook for the plugin 'Parameterized Builds' it displayes 'Unable to render configuration form for Parameterized Builds for Jenkins'. trigger cannot be configured.

How to reproduce:
- Have Bitbucket Server 6.0.0
- Update to plugin version 4.0.0 (previous version was installed)
- Create new Project
- Go to 'Project Settings'
- Go to 'Jenkins Settings'
- Any Values here always produce the same results, however I used 'Base URL' , Server Nickname and checked 'Build Token Root Plugin' and 'CSRF protection'.
- Go to Repositories
- Create new Repository
- Go to Repository Settings
- Go to Hooks
- It displayed 'Parameterized Builds for Jenkins' in disabled state
- Click on 'Disabled' to enable
- 'Unable to render configuration form for Parameterized Builds for Jenkins' is shown, trigger cannot be configured.

![grafik](https://user-images.githubusercontent.com/25386454/53394042-4fec1a00-399e-11e9-8949-ef48f9c81f03.png)

- Rebooting the instance after installing the plugin has not helped.
- Uninstalling the plugin, rebooting and installing 4.0.0 has not helped. Issue persists.

**Comment by a-hacker** [comment]
Can you try to uninstall and re-install the plugin? This will not delete any jenkins settings or hook configs you've already created.

**Comment by krm1** [comment]
I tried re-installing but it did not help. Is the plugin writing a log?

**Comment by a-hacker** [comment]
Unfortunately this isn't an issue with any of our code but something with Bitbucket. The same issue came up when v3.2.7 was released (see #162).

 I don't know exactly what is happening but it seems like Bitbucket is trying to use an old javascript file that no longer exists to render the job settings modal. However, I have not seen any bitbucket logs that confirm what is actually happening.

Under the Manage Apps tab, if you expand the `Parameterized Builds for Jenkins` section it should say there are 27 modules enabled. If you have more than that, disable any not in the following list:

![image](https://user-images.githubusercontent.com/3665996/53586937-38a45c80-3b57-11e9-96b4-ae8fc321ee95.png)

If that doesn't help, I'd contact Atlassian support and see if they have any ideas on how to resolve this issue.

**Comment by krm1** [comment]
I have 27/27 modules activated and they match your screenshot. Also tried uninstalling the plugin, removing all files left on disk that had '*parameterized*' in their name (in bitbucket/plugins/.osgi-cache/transformed-plugins/ and bitbucket/tmp/), but after a reboot and reinstall the issue was still there.

Do you contact Atlassian support or should I?

![grafik](https://user-images.githubusercontent.com/25386454/53620829-aa7eb380-3bf4-11e9-84cf-9135f15c274d.png)

**Comment by krm1** [comment]
@a-hacker Would it help if I were to setup a vanilla Bitbucket Server 6 instance, install the plugin and then import the old files (repos, config) to application_data?

**Comment by a-hacker** [comment]
I think that would work. I don't know how you use Bitbucket or how many projects and repositories you have but that sounds like a lot of work to migrate Bitbucket servers to fix this issue.

I can create a jar for you that implements a similar fix to the one in the issue I linked previously. I would not release this publicly unless other users report this issue and I would not maintain a separate set of releases (this would be a one time thing). However, if my understanding of the issue is correct, this would only need to be done once.

Would this be an acceptable solution for you?

**Comment by Codesmith1024** [comment]
Hey guys, I hate to say it, but I'm experiencing the same issue, but from after a server migration.

We were previously running Bitbucket 5.13.0, and after migrating the repo to another server successfully, it was upgraded to 6.0.1. After doing that I had to update this plugin, and now I'm running onto this issue on multiple repositories, _but not all of them_. Maybe this gives us a valuable debugging opportunity if you can point me to things to look at for differences between them.

If you think this is a separate issue, I can go open a new issue.

**Comment by ronhks** [comment]
I expreienced with Bitbucket 6.0 at new project configuration.

All of old one, works well.

I used Bitbucket 5.x previously.

**Comment by a-hacker** [comment]
@Codesmith1024 that's really interesting. The only code change to the Job Settings was the server nicknames. Did the repos with this issue have server nicknames populated? What about the repos that behave properly?

@ronhks have you added any server nicknames in your Jenkins settings?

Thank you all for the additional information. Now that I'm aware this is not a niche issue, I will try to investigate further and find a suitable fix. Unfortunately, I do not have access to a stable Bitbucket Server to test against so my troubleshooting abilities are somewhat limited.

**Comment by Codesmith1024** [comment]
@a-hacker Thanks for the reply, I assume you're referring to the Server Nickname property under the Jenkins settings. The two repos in question (one good and one bad) both are in different projects, both of which do have server nicknames populated. Additionally in the admin settings for the server as a whole there is a jenkins connection listed, but without a nickname.

In all three locations I can hit "Test Connection" and get a successful result. Removing the nicknames doesn't appear to have any affect, neither does setting all of the nicknames to the one the working project specifies.

**Comment by a-hacker** [comment]
@Codesmith1024, do both repos have jobs specified in the hook settings? If you look at your browser's console do you see any errors logged there?

**Comment by Codesmith1024** [comment]
@a-hacker 

> do both repos have jobs specified in the hook settings?

On the working repository, the only hook that is enabled is the Parameterized Builds for Jenkins. For the one that is broken, even that is disabled since I get the "Unable to render configuration" screen when I go to enable it.

> If you look at your browser's console do you see any errors logged there?

I'm not a web developer, so I'm not certain that I'm going about this the right way, but I navigated to the hooks page, opened the console, and then tried to go to the enable/configure page that gives me the error. This was the only thing that was logged:

```
Downloading resources:
js!/s/eed70f6c2ec546a3296db734e57bfcbb-T/-2112613955/07b7bcc/260/8a1ee925c404b45bb2294fa769035adf/_/download/contextbatch/js/com.kylenicholls.stash.parameterized-builds:parameterized-build-hook-config-form,-_super,-bitbucket.page.settings.hooks,-bitbucket.layout.repository,-atl.general/batch.js?locale=en-US!order
```

**Comment by a-hacker** [comment]
@Codesmith1024, thanks for quick update. Do you know if the broken repo had the parameterized builds for jenkins hook enabled before you migrated servers? I'm assuming that when you migrated servers the plugin settings were migrated as well. Is that true?

The jQuery message might be relevant. Could you send me a snapshot of your Jenkins Settings. If you don't feel comfortable posting that here, you can send it in an email to explosivepyrounicorns@gmail.com. I'm mostly curious if there are any special characters that could be causing an issue.

**Comment by Codesmith1024** [comment]
@a-hacker 

> Do you know if the broken repo had the parameterized builds for jenkins hook enabled before you migrated servers? I'm assuming that when you migrated servers the plugin settings were migrated as well. Is that true?

Yup! both repositories had parameterized builds enabled and working successfully before the server migration. After migration and app updates, the settings did retain their original values.

> Could you send me a snapshot of your Jenkins Settings. If you don't feel comfortable posting that here, you can send it in an email to explosivepyrounicorns@gmail.com. I'm mostly curious if there are any special characters that could be causing an issue.

Sent! You should have an email from flying.robotic.lymbs@gmail.com.

**Comment by krm1** [comment]
@a-hacker I can confirm, I get the same errors as @Codesmith1024. The jenkins hooks were enabled as well, this was never a problem in past updates in the Bitbucket Server 5.X family. Has it something to do with the installer of Bitbucket Server 6 deactivating all your plugins before updating?

![grafik](https://user-images.githubusercontent.com/25386454/53860137-4edf6c00-3fe0-11e9-974a-7b5b12dd2928.png)

**Comment by a-hacker** [comment]
I've created a jar with the same type of change as #163. The new jar is located [in the releases](https://github.com/KyleLNicholls/parameterized-builds/releases/tag/4.0.1-beta). Could one of you try manually installing this jar and see if it fixes your issues?

**Comment by Codesmith1024** [comment]
Sadly, I'm having no luck with it.

I uninstalled the one from the store, and installed your jar, and am having the same issue. Just to be sure I then uninstalled and reinstalled it again. It didn't break anything with the working repo, but it didn't fix anything with the broken repo either.

It is worth noting that for the broken repo, I am no longer getting the JSON parsing error, and I do still get the dowloaded resource message.

**Comment by ronhks** [comment]
@a-hacker of course. Prevviously (on Bitbucket version 5.X) we used it. Also, at 6.0.X we also use it, at configured projects/repos. 

The problem comes only, on new repos.

**Comment by Codesmith1024** [comment]
So maybe this is a dumb question, but is there a configuration file that is stored per-repo that contains the plugin settings that may have not migrated correctly that we can try to reset?

**Comment by a-hacker** [comment]
All the settings are stored in whatever backend database you have configured for your bitbucket server. If you connect directly to the database you should be able to run the following sql to get the hook settings for each repository:

```
select r.name, l.id, l.lob_data
from repository r
join sta_repo_hook h
on r.id = h.repository_id
join sta_shared_lob l
on h.lob_id = l.id
where h.hook_key = 'com.kylenicholls.stash.parameterized-builds:parameterized-build-hook'
```
It might be worth trying to remove the lob_data associated with a broken repo. However, I do not know what side effects this would have on Bitbucket. You should probably back up the table first.

**Comment by Codesmith1024** [comment]
Hmm... I'll keep it in mind, but that sounds too risky for me to want to test without a good reason...

**Comment by a-hacker** [comment]
I've created a support ticket with Atlassian about this. Hopefully, I'll know more soon.

**Comment by a-hacker** [comment]
Atlassian support is looking for more debug details. They have asked for the following:

Please enable debug logging at Administration >> Logging and profiling, reproduce the issue on one of the failing repositories, and attach a support zip to the ticket. Please also capture the network traffic during this time and attach a HAR file to the ticket. Please complete the above steps for a successful repository and attach the HAR file for that as well.

Would one of you be able to do this? If you have an atlassian account, I can share the support ticket with you. If you do not, please send my the requested files via email. Thank you all for your patience and your help as we get to the bottom of this.

**Comment by Codesmith1024** [comment]
@a-hacker You should have an email with HAR files and my work email for on tagging me in on the ticket!

**Comment by ronhks** [comment]
@a-hacker i sent also.

**Comment by Codesmith1024** [comment]
So interesting tidbit -- it was discovered that if we make a new project and repo, it works great, unless that new repo has a hyphen in the name. Removing the hyphen works great, and adding a hyphen to a working repo breaks it.

@ronhks @krm1 Do either of you guys have special characters in the repo/project that isn't working for you guys?

I'm still not sure why it would've worked in bitbucket 5.x, but not in 6.x...

**Comment by a-hacker** [comment]
@Codesmith1024 I'm able to replicate that! I think Bitbucket 5.X didn't allow hyphens in the repo slug but it looks like Bitbucket 6.X does. I think I should be able to test a fix later today.

**Comment by Codesmith1024** [comment]
@a-hacker Assuming that fix works, do you have a rough ETA as to when we would be able to get that fix? (I'm not sure what timezone you're in, and I've definitely had a different definition of "later today" than other people in the past lol)

**Comment by a-hacker** [comment]
I'm in eastern time USA and I'm currently at work. By later today, I mean when once I've gotten off work (usually 5-6 PM ET). Hopefully all goes well and testing only takes ~30 minutes. It may take longer though in which case I couldn't say when I'll be done.

**Comment by Codesmith1024** [comment]
Thanks! I'm just looking for something rough, and I definitely know that things tend to stretch out.

**Comment by ronhks** [comment]
I think the hyphens a good idea. We had in Bitbucket 5.X repo-s with hyphens BUT! these repos not configured to jenbkins yet. And at Bitbucket I created a new repo (also with hyphens in name) and when I tried to configure that to jenkins i got the error. So, cross fingers! :) And, of course, thanks the work!

**Comment by a-hacker** [comment]
Yeah, repository names could always have hyphens but Bitbucket would also create a repository slug to identify the repo as well. This slug would often be a 4-5 uppercase character string with more restrictive naming rules. I don't recall if hyphens were allowed but I think it could only by alphanumeric and underscore characters.

It looks like the slugs were phased out in newer versions of 5.X but since I had been developing against 5.4.0 I didn't catch that in some code that was unreleased until the v4.0.0 update.

**Comment by a-hacker** [comment]
I've updated the jar in the [4.0.1 pre-release](https://github.com/KyleLNicholls/parameterized-builds/releases/tag/4.0.1-beta). I believe it will fix this issue.

**Comment by krm1** [comment]
@Codesmith1024 @a-hacker Yes, i had a hypen in the repository name and in the project name. If I create a new project without hyphen and a repository without hyphen it works. If the repository has a hyphen in the name it gets the error. However in previous versions this wasn't a problem for the plugin, we have many repositories with hyphen which worked fine with the old plugin on Bitbucket Server 5.X.

**Comment by Codesmith1024** [comment]
@a-hacker It looks like that has worked out our issues over here!

**Comment by a-hacker** [comment]
This issue has been fixed in version 4.0.1. Thank you all for your help through this issue. If the problem persists after upgrading, please re-open this issue.

**Comment by Codesmith1024** [comment]
Make sure to close the atlassian ticket as well!

**Comment by krm1** [comment]
@a-hacker I can confirm, 4.0.1 resolves the issue. Thank you for fixing it. :)

**Comment by knoobie** [comment]
@a-hacker Before I create a new issue, some of our projects have a blank screen after migration to the latest version, because of a '.' (dot) in the repository name (example: company.project). I would be awesome if this char can be added as well! Thanks!

**Comment by a-hacker** [comment]
Hi @knoobie. Sorry for the delay. Version 4.0.2 has been released with a fix.

**Comment by carminevassallo** [comment]
Hi @a-hacker,

I'm experiencing the same _render configuration form_ issue that @krm1 and the others were facing a few versions ago. I have the following bug:

Parameterized Builds for Jenkins_ plugin version: 5.2.0
Bitbucket_ version: 7.4.0
Jenkins_ Version: not relevant
Detailed description of the issue: the plugin "Parameterized Builds for Jenkins" can't be configured on private repos (repos on your user rather than on a project - doesn't mean that the repo can't be visible to other users), it just shows "Unable to render configuration form for Parameterized Builds for Jenkins".

How to reproduce the issue:
1. log in to bitbucket
2. go to your own profile
3. click on "create repository"
4. give it some name and create it
5. go to the settings of that repo
6. go to "hooks"
7. try to enable "Parameterized Builds for Jenkins"

**expected**: the config dialog for that plugin/hook opens
**reality**: the mentioned error ("Unable to render configuration form for...") is shown instead
