### ISSUE TITLE
PUSH Trigger not building jenkins job

### ISSUE THREAD

**Issue by iamjsed** [KyleLNicholls/parameterized-builds#188]
Hi,

We've been using this plugin for more than a month now.  Then on April 4, 2019 Jenkins job is no longer getting triggered by a PUSH EVENT on a feature branch.  

Bitbucket Server v5.11.1
Jenkins ver. 2.164.1
Jenkins Parameterized Build 3.2.6

all we can find in the logs is this which does not tell us much.

```10.1.192.33 | RepositoryHookSettingsChangedEvent | julius.sediolano | 1554443336011 | com.kylenicholls.stash.parameterized-builds:parameterized-build-hook | {"project":"UAP","repository":"horizon-core","hook":"com.kylenicholls.stash.parameterized-builds:parameterized-build-hook","settings":{"jobName-0":"deploy-uap-horizon-core-endpoint","isTag-0":"false","triggers-0":"push;","token-0":"TRIGGERFORLAMBDADEPLOYMENT","buildParameters-0":"BRANCH=$BRANCH\r\nCOMMIT_HASH=$COMMIT\r\nTRIGGER=$TRIGGER\r\nREPOSITORY=$REPOSITORY","branchRegex-0":"","pathRegex-0":"","requirePermission-0":"REPO_READ","prDestinationRegex-0":""}} | @11DVPS6x48x245539x1 | 18n2kef```

**Comment by a-hacker** [comment]
Hi @iamjsed,

Is this an issue with a specific branch or all branches? Do other trigger types still work and if so which ones? It looks like that log indicates a settings change. Do you recall what was changed?

**Comment by a-hacker** [comment]
Due to inactivity, I am closing this issue. Please comment with additional details if this is still an issue.
