### ISSUE TITLE
how to properly set up PR build with forks?

### ISSUE THREAD

**Issue by rursprung** [KyleLNicholls/parameterized-builds#194]
i'm not quite sure whether this is a bug or a missing feature...

# goal
we try to have the "classical" forking setup as it is also used on GitHub:
- repo "repoX" under organisation "org1" as the upstream
- 1..n forks ("repoX") under users ("~user1"; or, seldom, organisations ("org2"))
- nobody has push access to upstream, all code merges must happen through pull requests
- contributors fork the upstream repo, push their work to a branch on their fork and then create the PR from there (e.g. "~user1/repoX > my-new-feature" wants to merge back to "org1/repoX > master")

# problem / reproduction
however, i fail to set up the verify build for the PRs correctly. our setup only works in case the PR comes from within the same repo (e.g. "org1/repoX >my-new-feature" wants to merge back to "org1/repoX > master").

i initially believed that this is what was reported in #119 and fixed in #127 and we made sure to run a newer plugin version which contains that fix (which is why we just upgraded to 3.2.10), but it didn't help.

we trigger the jenkins build with the following parameters:
branch=$BRANCH
repository=ssh://git@bitbucket.example.org/$PROJECT/$REPOSITORY.git

however, $PROJECT and $REPOSITORY always get replaced with the project of the repo on which the PR is opened (the upstream repo). thus jenkins will fail to find the branch since it's cloning the wrong repo.

i tested the following setups:
* PR from one branch to another within the same repo: works
* PR from a repo to another repo within the same organisation (only $REPOSITORY would be different): doesn't work
* PR from a repo within one user/organisation to a repo within another user/organisation ($PROJECT would definitely be different, $REPOSITORY might be): doesn't work

i went through the documentation for all variables, but couldn't figure out how to set it up. i do not see any variable which is "source repo URL" or "source repo project" + "source repo name".

# presumed solution approach
is there currently a way to set up this standard use-case? or is this missing? if it is missing, am i right in presuming that it'd be as simple as introducing the new PR-specific variables (naming might be a bit off here) $PRSOURCEPROJECT $PRSOURCEREPOSITORY ?

# versions currently in use
* parameterized-builds: 3.2.10
* bitbucket: 5.4.8
* jenkins: 2.121.1

**Comment by a-hacker** [comment]
Hi @rursprung. You are correct that $PROJECT and $REPOSITORY are specific to the target repository, not the source repo. There are no variables for the source repo currently available but I think your proposal is reasonable and worth doing.

Currently we only support updates for Bitbucket Server 6 versions though.

**Comment by rursprung** [comment]
thanks for your feedback @a-hacker!

i'm actually wondering if my proposed solution isn't the wrong way around: shouldn't the configuration for the build always have the source repo information in the same variables regardless of whether it's a PR or a build on the repo itself (e.g. after merge)?
in that case `$REPOSITORY` & `$PROJECT` should be the *source* repo in case of a PR. for any existing consumer this *should* stay the same since the fork setup is currently anyway not supported.
and then new variables will be introduced for the target repo (might be relevant to the job - though for a simple verify it is not relevant): `$PRTARGETPROJECT` and `$PRTARGETREPOSITORY`

what is your opinion on this?

do i see it correctly that implementing this functionality (in either way) would be localised in `BitbucketVariables` + `BitbucketVariablesTest` and be done with a few lines of code? (i just quickly browsed through the code on github, didn't check it out (yet) - i might have missed something important :))

**Comment by a-hacker** [comment]
I agree that it would make more sense for the source repo and project use for `$REPOSITORY` and `$PROJECT` respectively. However, making this change would cause a change in behavior for current users. For instance, a user may have a jenkins job that does not need to clone the branch but needs to run when a PR is opened and needs to know what repo the PR was opened on. Although this is a bit more niche, I'd rather implement a solution that is will not break existing workflows when possible.

You are right that the `BitbucketVariables` and associated tests are all that should need to be updated. The only real gotcha there is that the new variable names need to be added to the `SET_VALUES` attribute.
