### ISSUE TITLE
jenkins server admin GUI not working after refactoring

### ISSUE THREAD

**Issue by rursprung** [KyleLNicholls/parameterized-builds#196]
commit c22af8bebcff9ee5a57bc96fbd332b1763122ee5 breaks the admin GUI
to reproduce:
* clone the repo
* run it locally `atlas-run.bat -u 8.0.0 -Dmaven.javadoc.skip=true`
* open the admin GUI (the global or a project-specific one - both have the same problem)

expected: jenkins server admin GUI works
current result:
the following error is written to the console of the web browser:
```
TypeError: Cannot read property 'alias' of undefined
    at T (server_form.js?_statichash=d41d8cd98f00b204e9800998ecf8427e-CDN%2F-1794069248%2F811079b%2F1%2F4.0.3:46)
    at E (server_form.js?_statichash=d41d8cd98f00b204e9800998ecf8427e-CDN%2F-1794069248%2F811079b%2F1%2F4.0.3:46)
    at S (server_form.js?_statichash=d41d8cd98f00b204e9800998ecf8427e-CDN%2F-1794069248%2F811079b%2F1%2F4.0.3:46)
    at C (server_form.js?_statichash=d41d8cd98f00b204e9800998ecf8427e-CDN%2F-1794069248%2F811079b%2F1%2F4.0.3:46)
    at Object.v [as dispatch] (server_form.js?_statichash=d41d8cd98f00b204e9800998ecf8427e-CDN%2F-1794069248%2F811079b%2F1%2F4.0.3:1)
    at server_form.js?_statichash=d41d8cd98f00b204e9800998ecf8427e-CDN%2F-1794069248%2F811079b%2F1%2F4.0.3:46
```

note: this was pre-discussed in #195

**Comment by rursprung** [comment]
@a-hacker: i rebased and did a completely new build and the admin GUI still doesn't work - i still get the exact same exception.
can you please re-open the issue and look into it again?

**Comment by a-hacker** [comment]
@rursprung, did you push the rebased code? It looks to me like your branch does not contain the commits from #202.

**Comment by a-hacker** [comment]
@rursprung. Another thing is that you might need to go into `Manage Apps` in the Bitbucket Admin settings and manually re-upload the jar. For whatever reason Bitbucket Server seems to occasionally cache old javascript files and use those instead of the new ones.

**Comment by rursprung** [comment]
since i deleted the whole `target` folder that shouldn't be necessary, but i tried it anyway to no avail. however, i still got one step further because i realised that there was some local browser caching which i have now disabled/cleared and with that the new script is used.

but now trying to safe the settings fails with a HTTP 405:
the UI tries to `PUT` to http://localhost:7990/bitbucket/rest/parameterized-builds/latest/global/servers/
but this method isn't implemented (thus a 405).

acc. to `ServerService` a `PUT` is only implemented if the server is part of the URL (which makes sense - otherwise it'd be a POST - but that isn't implemented either):
```java
    @PUT
    @Path("/servers/{serverAlias}")
```

to reproduce:
# use a clean build with no existing settings (just drop the `target` folder)
# open the jenkins settings admin page
# enter a new base URL + server nickname
# hit "save" => HTTP 405
# also try "clear jenkins settings" => same error

since the JS code in `rest.js` clearly tries to add `${alias}` to the URL this is still a JS bug with the code which you have modified.

you should be able to easily reproduce this problem and hopefully fix it (since i'm not too familiar with JS and don't have the time i won't dig into your code).

**Comment by rursprung** [comment]
note: as a workaround you can use the devtools of your browser and execute this JS code snippet which does the same request:

```js
fetch('http://localhost:7990/bitbucket/rest/parameterized-builds/latest/global/servers/example', {
    method: 'PUT',
    body: JSON.stringify({"baseUrl":"http://jenkins.example.org/","alias":"example","user":"","token":null,"altUrl":false,"csrfEnabled":false}),
    headers: { 'Content-type': 'application/json' }
}).then(console.log);
```

**Comment by a-hacker** [comment]
Missed a null check. Fixed it and actually verified saving works.
