### ISSUE TITLE
improve code quality: add & enforce checkstyle

### ISSUE THREAD

**Issue by rursprung** [KyleLNicholls/parameterized-builds#197]
currently, the codebase has a mixture of various coding styles, making it harder to read.

i would suggest to add [checkstyle](https://checkstyle.sourceforge.io/) to the codebase. what would have to be done for that:

- [ ] decide on a specific coding guideline to use (there are various, the ones from Sun & Google maybe being the more prominent)
- [ ] use an editor with checkstyle support (for both IntelliJ and eclipse plugins exist for this, the same is probably true for other editors as well) and check all findings and fix them (either in one big commit or multiple smaller commits)
- [ ] enable the [checkstyle maven plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html) to prevent the integration of any code which does not follow the defined styleguide
- [ ] maybe do some Travis CI config changes to properly expose the checkstyle report (not sure if this is needed - i have never used checkstyle in combination with Travis CI)
- [ ] update the developer docu to point out that checkstyle is used and specify how it can be set up for common IDEs (they then auto-format with those settings)
- [ ] possibly add an [editorconfig](https://editorconfig.org/) file as well with some basic settings to make life easier

(this was opened based on the discussion in #195)

**Comment by rursprung** [comment]
note: checkstyle is only here for java. for the JS & related web code other tools exist, but i'm not at all familiar with them. it might make sense to set them up as well

**Comment by a-hacker** [comment]
@rursprung, checkstyle has been added to the project. I decided to write my own guidelines with only a few rules. Consistency is good but I don't want anyone to feel restricted by the guidelines. I figure it can expand more naturally in the future.
