### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by karbassi** [KyleLNicholls/parameterized-builds#2]
Hey @KyleLNicholls, we're using your plugin and are running into some troubles getting it configured. We wanted to see what we did wrong but this github repo isn't your latest code.

You have 1.0.1 on here, and 1.0.2 on atlassian. Do you think you could update the repo?

**Comment by KyleLNicholls** [comment]
Sorry, forgot to push and I don't really maintain this plugin anymore.
