### ISSUE TITLE
parameterized-client/package-lock.json not part of repo and neither in .gitignore

### ISSUE THREAD

**Issue by rursprung** [KyleLNicholls/parameterized-builds#200]
after running a full build using `atlas-run` the following untracked file appears:
parameterized-client/package-lock.json

it is my understanding that the NPM lock file should generally be integrated in the repo so that all builds have the same version and dependency updates are properly tracked.
if, for some reason this shouldn't be the case here i suggest to add it to `.gitignore` and add a comment as to why this is the case.

**Comment by a-hacker** [comment]
There really isn't a reason for the package-lock.json to be excluded. This project was my first real experience with node and I wasn't sure if it should be committed or not.

**Comment by a-hacker** [comment]
package-lock.json added to repo.
