### ISSUE TITLE
atlas-run.bat fails on windows w/o specifying amps version explicitly

### ISSUE THREAD

**Issue by rursprung** [KyleLNicholls/parameterized-builds#203]
tested with current master build of the repo.

as noted in #195 i was forced to run `atlas-run.bat -u 8.0.0` rather than just being able to run `atlas-run.bat`. with a completely new plugin (created using `atlas-create-bitbucket-plugin.bat`) this problem didn't exist.
i debugged this a bit and now found the problem: the `pom.xml` in this repo is using tabs rather than spaces and this messes up the logic in `atlas-run.bat` which tries to extract the version number from the `pom.xml` and does not expect tabs but only whitespaces.

while this should probably be fixed in the atlassian SDK at some point, there's IMHO no valid reason to use tabs in the `pom.xml` (or anywhere in software engineering :)), so i'd suggest to just switch the file to whitespaces and then this will work fine.

i have reported the root cause to the atlassian SDK: https://ecosystem.atlassian.net/browse/ATLASSDK-185

**Comment by a-hacker** [comment]
I prefer to use spaces too. Converting the indents should be easy enough. Would you prefer to make this change or should I?
