### ISSUE TITLE
"Parameterized builds for jenkins" UNSUPPORTED???

### ISSUE THREAD

**Issue by kdatta10** [KyleLNicholls/parameterized-builds#209]
Currently this shows as "UNSUPPORTED". Is there any alternative way to trigger manual build from bitbucket with some parameters?

**Comment by a-hacker** [comment]
Hi @kdatta10. I assume you are referring to the "unsupported" tag on the Atlassian Marketplace page. This tag does not mean that there will be no new updates or bug fixes to the plugin or that the project is orphaned. Unsupported is simply a classification of apps that are not supported directly by Atlassian. You can see more details here: https://confluence.atlassian.com/support/atlassian-supported-apps-229836119.html
