### ISSUE TITLE
Unable to trigger parameterized Jenkins Job 

### ISSUE THREAD

**Issue by h2oboy** [KyleLNicholls/parameterized-builds#211]
Hi,

- _Parameterized Builds for Jenkins_ plugin version: **4.0.3**
- _Bitbucket_ version: Local Windows Server **v6.3.2**
- _Jenkins_ Version: Local Windows Server **2.185**
- Detailed description of the issue

**I have the following issue**

I tried to trigger a simple parameterized (1 parameter)  jenkins job ( details down below) and the job was not event started. I do know how to findout if the actual job  build request was sent or not.

**Jenkins Settings (Bitbucket)**  

      Base URL -> http://myjenkins.local/jenkins
      Server Nickname -> MyJenkins
      Default User -> tuser
      Default Token -> 1197084e4d98207d89d42ca05df15ec333
      CSRF protection -> Enabled

I saved the configuration and Tested Jenkins Settings and the **Connection successful!**

**Parameterized Builds for Jenkins (Bitbucket)**

     Job Name -> test
     Jenkins Server -> MyJenkins
     Ref Type -> branch
     Multibranch pipeline -> Enabled
     Triggers -> Enable all of them
     Token -> wtthothuothuththtg
     Build Parameters -> GIT_BRANCH=$BRANCH
     Required Build Permission -> Read   

**Job (Jenkins)**
 
I created a simple freestyle job to test the communication. This job has the following parameters:

    This project is parameterized -> Enabled
       String Parameters 
           Name -> GIT_BRANCH

     Trigger builds remotely (e.g., from scripts) -> Enabled
         Authentication Token -> wtthothuothuththtg

     Execute Windows Batch Command
         Command -> echo %GIT_BRANCH%

**Things that  I tried:**

I ran the following command on the Bitbucket Server, to verify the communication between both servers (jenkins/bitbucket)

    curl -X POST "http://myjenkins.local/jenkins/job/test/buildWithParameters?GIT_BRANCH=master&token=wtthothuothuththtg" -u tuser:1197084e4d98207d89d42ca05df15ec333

The job was executed on jenkins without any issues

**Comment by a-hacker** [comment]
@h2oboy, try disabling mulitbranch pipeline. That option is only meant for [Multibranch Pipeline](https://jenkins.io/doc/book/pipeline/multibranch/#creating-a-multibranch-pipeline) style jobs.

**Comment by h2oboy** [comment]
I remove it and that did the trick. My mistake! apologize
