### ISSUE TITLE
Getting java.lang.NullPointerException: null when trigger build from bitbucket 6.2.0 

### ISSUE THREAD

**Issue by gwsu2008** [KyleLNicholls/parameterized-builds#213]
Hi,

I ran into an issue with starting a build from bitbucket. The atlassian bitbucket log attached.

- _Parameterized Builds for Jenkins_ plugin version: 4.0.3
- _Bitbucket_ version: 6.2.0
- _Jenkins_ Version: 2.176.2

![Error_popup](https://user-images.githubusercontent.com/11874389/61900436-71f8b280-aed2-11e9-9cbc-23c41d5d802c.png)

[bitbucket-error-start-build.log](https://github.com/KyleLNicholls/parameterized-builds/files/3432858/bitbucket-error-start-build.log)

Thanks

--Guang

**Comment by a-hacker** [comment]
Hi @gwsu2008. If you have not added a nickname to your jenkins server definition yet and updated your hook settings to use the given servers, this should fix your issues.

If you have made these changes already, make sure your job definitions in the hook settings are not referring to a deleted jenkins server. This would cause the error you reported.

**Comment by gwsu2008** [comment]
Hi,

Yes. I added a nickname for the jenkins server and hook works again. It's not a bug.

Thanks.
