### ISSUE TITLE
BitBucket Variables not being evaluated

### ISSUE THREAD

**Issue by edwardtew** [KyleLNicholls/parameterized-builds#22]
I have a Bitbucket server with the following configuration 
![image](https://cloud.githubusercontent.com/assets/19808346/15880369/ae93037a-2d80-11e6-805a-b7c8b2086b8e.png)
but when the jenkins job is scheduled the parameters  are not evaluated before being passed to the Jenkins server.
![image](https://cloud.githubusercontent.com/assets/19808346/15880656/a6c19bae-2d83-11e6-9a00-348b1226ba8e.png)

These are not being evaluated by the BitBucket Plugin before sending to Jenkins.
$PRDESTINATION
$PROJECT
$REPOSITORY

**Comment by edwardtew** [comment]
am I doing something wrong ?

**Comment by KyleLNicholls** [comment]
Looks like a bug

**Comment by KyleLNicholls** [comment]
released v2.5.1 to the marketplace

**Comment by edwardtew** [comment]
installing and trying now

**Comment by edwardtew** [comment]
Nice quick work. :thumbsup:

Build from Pull request   :white_check_mark:

![image](https://cloud.githubusercontent.com/assets/19808346/15912047/66f83188-2e26-11e6-8fe4-7d0b2fa4a28b.png)

Build From Branch :warning:
![image](https://cloud.githubusercontent.com/assets/19808346/15912149/e3642cb8-2e26-11e6-959e-65eba3f150b6.png)

Preferably if the variable is not specified it would evaluate to an empty string so that the receiving job will be able to detect it and then the same job can be used for both Pull request builds or Branch Builds.

**Comment by KyleLNicholls** [comment]
Yeah I thought about that as well but that will take a bit more effort to change. It is also is a separate issue and needs some grooming. I opened an issue for it #24

**Comment by sdmoralesma** [comment]
Will you backport this fix to 1.4 branch?

**Comment by KyleLNicholls** [comment]
I will not, if someone wants to open a PR though I'll publish the fix.
