### ISSUE TITLE
Server URL context gets stripped out

### ISSUE THREAD

**Issue by hasterhorb** [KyleLNicholls/parameterized-builds#221]
Bug

- _Parameterized Builds for Jenkins_ plugin version
4.0.4, 4.0.5
- _Bitbucket_ version
6.5.1
- _Jenkins_ Version
2.32.2

When running Jenkins behind a proxy, with URL context in the server adress, the URL context get stripped out resulting in "Job not found" error.

When specifying **http://ci.domain.com/jenkins** as the server URL, the resulting contructed URL will be :

**/job/arqtest/buildWithParameters?FEATURE_NAME=mytest**

but should be

**/jenkins/arqtest/buildWithParameters?FEATURE_NAME=mytest**

It works as expected in v 4.0.3.

**Comment by 0x6e3078** [comment]
We run into the same issue here:
`x.z.y.a - jenkins [04/Sep/2019:15:54:08 +0200] "GET /jenkins/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb) HTTP/1.1" 200 795 "-" "Java/1.8.0_222"
x.z.y.a - jenkins [04/Sep/2019:15:54:08 +0200] "POST /job/GitBuilds/job/BuildMprm/buildWithParameters?<parameters> HTTP/1.1" 302 1194 "-" "Java/1.8.0_222"`

for the CRUMB the URL is correct and for the POST to trigger the Build Job the jenkins is removed from the configured URL.

**Comment by h2oboy** [comment]
Same here and somehow the token is gone on the POST msg. I am using wireshark to monitor the payload and the token is gone :-/.

I supposed to see myjenkins/job/test4/buildWithParameters?GIT_BRANCH=master&token=mytoken
but instead I see on the POST job/test4/buildWithParameters?GIT_BRANCH=master

The plugin is broken :-/

**Comment by h2oboy** [comment]
@gnustavo how do you downgrade ?

**Comment by gnustavo** [comment]
@h2oboy I followed [these instructions](https://confluence.atlassian.com/upm/updating-the-universal-plugin-manager-273875702.html#UpdatingtheUniversalPluginManager-Stash/BitbucketServer).

But they seem to be out of date with respect to the directories mentioned. I actually found the plugin under `<BITBUCKET_HOME>/plugins/.osgi-cache/transformed-plugins/plugin.9183878825831230814.parameterized-builds-4.0.5_1566777136000.jar`.

**Comment by h2oboy** [comment]
@gnustavo thank you 👍

**Comment by a-hacker** [comment]
In my test environments I just uninstall the current plugin and then manually install an older jar from [here](https://marketplace.atlassian.com/apps/1213179/parameterized-builds-for-jenkins/version-history) or the github [releases page](https://github.com/KyleLNicholls/parameterized-builds/releases). Prior settings will persist even with the uninstall. This is using the atlassian standalone instance though. I'm not sure if actual bitbucket servers would differ.

**Comment by h2oboy** [comment]
@a-hacker as you mentioned, I uninstalled 4.0.5 and manually install 4.0.3. That brings back to life the plugin

**Comment by a-hacker** [comment]
I've just published version 4.0.6 to fix this issue. I didn't have a great way to test this issue though so I've posted the new version as a beta version. If any of you can test the new version and verify this issue is fixed, I'll remove the beta flag.

**Comment by h2oboy** [comment]
@a-hacker I tested by creating a branch and it triggers the jenkins job (parametrizated build w/ 1 parameter GIT_BRANCH=master) and is broken. I tested using 4.0.3 and no issues.

**Comment by a-hacker** [comment]
@h2oboy, I think I accidentally published the wrong jar file. Could you download the 4.0.7 jar from the [github release page](https://github.com/KyleLNicholls/parameterized-builds/releases/tag/4.0.6) and try that one? For now, I've pulled the 4.0.6 release on the Bitbucket marketplace.

**Comment by h2oboy** [comment]
@a-hacker I ran the same test using 4.0.7 and same result as 4.0.6. I downgraded it to 4.0.3 and no issues

**Comment by a-hacker** [comment]
I'm pretty confident that the new 4.0.7 release resolves this issue. If the issue persists after upgrading, I'll need someone else to work on a fix because I don't have a proper way to test this scenario.

**Comment by 0x6e3078** [comment]
I tested 4.0.7 release yesterday and it seems to work like the 4.0.3, thank you for the fix.
