### ISSUE TITLE
Add email address of the author of the PR - build parameter

### ISSUE THREAD

**Issue by DnZmfr** [KyleLNicholls/parameterized-builds#225]
Hi everyone,

We are a team of about 20 developers and currently the failing PR jenkins pipeline builds are sent to the whole team, as the email address is hardcoded.
This is something that not everyone wants. The build result should be sent to the author of the PR so for this it would be great if the plugin could retrieve the email address of the author of the PR.

Cheers,
Dan

**Comment by a-hacker** [comment]
Hi @DnZmfr. That sounds reasonable. It should be pretty simple to implement too.

**Comment by DnZmfr** [comment]
I already implement it. Will create a pull request in few minutes.

**Comment by twistedvip** [comment]
Is there any reason why this cannot be used for MANUAL triggers? We are using the MANUAL trigger and would love to at least have the PREMAIL available so that I have the information for sending the email from my jenkins job.

**Comment by a-hacker** [comment]
@twistedvip, PREMAIL should be available when using a manual trigger from a pull request page. However, this variable will be populated with the pull request author's email address and not the user who triggers the job.

**Comment by a-hacker** [comment]
Released in 4.0.7
