### ISSUE TITLE
Support multiple instances of Jenkins

### ISSUE THREAD

**Issue by derliebemarcus** [KyleLNicholls/parameterized-builds#23]
For several setups it might make sense to use not only a single Jenkins but several. Therefore, it would be super awesome if one had the choice to select the Jenkins instance that shall run a job, wouldn't it?

**Comment by KyleLNicholls** [comment]
I did add support for defining Jenkins servers at the project level so different projects can use different Jenkins servers. Is that adequate or do you need multiple global Jenkins servers?

**Comment by derliebemarcus** [comment]
Hi there, thanks for the fast reply. Per-Project totally fits our needs. Thanks for the awesome plugin, btw!
