### ISSUE TITLE
Handle empty/null bitbucket variables

### ISSUE THREAD

**Issue by KyleLNicholls** [KyleLNicholls/parameterized-builds#24]
Preferably if the [$PRDESTINATION] variable is not specified it would evaluate to an empty string so that the receiving job will be able to detect it and then the same job can be used for both Pull request builds or Branch Builds.

Questions: 

- does Jenkins throw away build parameters that are empty or do we need to remove the params from the query?
- should the manual build prompt hide empty parameters from users (could have unwanted side effects)?

**Comment by edwardtew** [comment]
Jenkins creates environment variables when passing parameters to scripts. We use Bash as the main script interpreter and when the parameter is set to an empty string it is not unset.

**Comment by edwardtew** [comment]
> should the manual build prompt hide empty parameters from users (could have unwanted side effects)?

No, the user has defined a variable that will be passed to the Jenkins builder and the bitbucket plugin has determined that it is empty so it should be passed as an empty string

**Comment by KyleLNicholls** [comment]
release in v2.6.0
