### ISSUE TITLE
Support for Bitbucket Server 4.0

### ISSUE THREAD

**Issue by avthart** [KyleLNicholls/parameterized-builds#3]
We are planning to upgrade our Stash 3.8 installation to Bitbucket Server 4.0
Is Bitbucket Server 4.0 supported? If not, do you have any plans to test and support this?

Thanks!

**Comment by KyleLNicholls** [comment]
4.0 is not supported and I have no plans to support it at this time. I am taking PRs if anyone wants to help update it.

**Comment by avthart** [comment]
@KyleLNicholls Thank you for answer. We decided to build our own plugin for Bitbucket Server.

**Comment by KyleLNicholls** [comment]
@avthart If you still want it, I just published version 2.0.0 with bitbucket server support.

**Comment by avthart** [comment]
@KyleLNicholls Thanks!
