### ISSUE TITLE
Cant send = as value

### ISSUE THREAD

**Issue by otbe** [KyleLNicholls/parameterized-builds#35]
Hi,

is there some way to send a value with one or more equal signs in it? Something like

Build Parameters:
```
MESSAGE=My cool message with <a href="google.com">link</a>
```

Thanks!

**Comment by KyleLNicholls** [comment]
Not currently but it should be an easy fix

**Comment by uweschaefer** [comment]
we're on it

**Comment by KyleLNicholls** [comment]
release in v2.6.0
