### ISSUE TITLE
Pushing a new branch with commits does not trigger a build with BRANCH CREATED trigger disabled

### ISSUE THREAD

**Issue by randomcoder** [KyleLNicholls/parameterized-builds#37]
We have the plugin setup to only enable the `MANUAL` and `PUSH EVENT` triggers for a build. The issue is caused when a branch is created by a developer locally on their machine (not on the bitbucket server) and later pushed to our bitbucket server with commits on the new branch.

It seems the trigger is only looking at the `BRANCH CREATED` event and then stopping as this event is disabled. It is not continuing to look for the PUSH EVENT trigger that we would expect to also be activated in this case.

Many Thanks,

**Comment by KyleLNicholls** [comment]
You'll need to enable `REF CREATED` event in the plugin since you are pushing a new branch. It's a Bitbucket/stash implementation. Bitbucet will trigger only the branch created event if you push a new branch, regardless if there are commits on the branch.
