### ISSUE TITLE
Question rather then issue

### ISSUE THREAD

**Issue by pmbsa** [KyleLNicholls/parameterized-builds#40]
Hi, Is there by any chance a parameter in the request sent to jenkins that will tell the job what type of event has created the trigger? (if that makes sense? I want to know if it was a PUSH event, MANUAL, PR EVENT etc. in the jenkins job if at all possible)

thanks
Paul

**Comment by KyleLNicholls** [comment]
There is not, sorry.
If someone wants to add that thought, it would be a good idea

**Comment by KyleLNicholls** [comment]
release in v3.1.1
thanks for adding this @a-hacker
