### ISSUE TITLE
Another question rather than issue

### ISSUE THREAD

**Issue by EmileDavies** [KyleLNicholls/parameterized-builds#41]
Hi Kyle

Plugin is working sweetly, just wondering though is there any way to pass from the Pull request to Jenkins the email address of the user actually kicking off the build. Not the author of the commit or pull request but the actual person running the build

Reason I ask is that in our workflow we have a triggered build for every pull request and update. That build compiles, unit tests and creates an artefact. However it is then down to the testers to login to those pull requests, when assigned, and use this plugin to kick off another build which deploys the artefact (ear) to an environment to carry out functional testing. This build deploys, runs confidence tests, automated regression and a few other integration tests. 

What were missing is the ability to email the exact tester who kicked off the build from this plugin, that the environment is ready for them to use.

thanks

Emile

**Comment by schniedergers** [comment]
+1 from me. Getting the PR author's email address via env variable would be very useful, as our triggered jobs should send an email notice to PR authors.

**Comment by edwardtew** [comment]
The jenkins usernames and the BitBucket usernames do not necessarily need to be managed through the same user directory.

The jenkins job can make additional Rest Ali calls to BitBucket to retrieve the email address of the user starting the job based on the name provided in the parameters.

I manipulate the url parameter to get the rest api for the PR itself and then jenkins connects on the PR as a user and BitBucket notifies everyone involved of the results of the jenkins job.

I also use the commit hash to display a build status against the commit in BitBucket.

**Comment by KyleLNicholls** [comment]
If the user triggering the build has linked their Jenkins account to bitbucket via http://server:7990/bitbucket/plugins/servlet/account/jenkins then the build will be started in Jenkins by whoever triggered it in Bitbucket. In Jenkins you can specifically email whoever triggered the build (email-ext plugin in Jenkins)
