### ISSUE TITLE
Only PRDestination is available

### ISSUE THREAD

**Issue by RasmusVoss** [KyleLNicholls/parameterized-builds#42]
Hi 

I am trying to pass all the PR specific parameters to my jenkins build but only pr destination is coming through correctly
The rest of the PR specific values are just coming through as $PRDESCRIPTION and so on 

I have the latest version of the plugin, 
but in the help description i can only see prdestination 
Key=Value pairs separated by new line. For choice parameters separate values with a semicolon. Available Bitbucket variables: $BRANCH, $COMMIT, $PRDESTINATION (only used for the PR triggers), $REPOSITORY, $PROJECT

Am i doing something wrong or is this an issue.

**Comment by mrMagicCod3r** [comment]
I have similar problem. I'm trying to pass $PRID parameter to jenkins as documented here https://github.com/KyleLNicholls/parameterized-builds#build-parameters and also no success.

**Comment by mike10010100** [comment]
Bump. This is hugely important for being able to post back results to Bitbucket.

**Comment by KyleLNicholls** [comment]
release in v2.6.0
