### ISSUE TITLE
Issue with BitBucket 4.10

### ISSUE THREAD

**Issue by devalru** [KyleLNicholls/parameterized-builds#43]
env:
BitBucket 4.10 Server on SLES12
Param. Build. Plugin Version 2.5.2
Jenkins 1.609.3

After Upgrading to BitBucket 4.10 and Plugin Version 2.5.2 the jobs are not triggered at all.
We run Jenkins behind nginx so I enabled the access logs and analyzed the request.
No build request is incoming.

**Comment by KyleLNicholls** [comment]
Are there any errors in the bitbucket UI or bitbucket logs when attempting to trigger a build?

**Comment by devalru** [comment]
I got it. The BitBucket update *overwrites* the bitbucket/bin/env-Script. Proxy-Settings lost. 
You can close the issue.
