### ISSUE TITLE
MANUAL Trigger Passes Parameters from PR but PR_OPENED doesn't

### ISSUE THREAD

**Issue by edwardtew** [KyleLNicholls/parameterized-builds#44]
Hi Kyle,
    Thanks for the latest update.

With the configuration below I was able to get all the parameters from the Pull Request into the Jenkins Job when the job was manually triggered from the "Build in Jenkins" button

![image](https://cloud.githubusercontent.com/assets/19808346/19505217/49ef3a3c-961d-11e6-9ef1-8c0f2f3db60e.png)

**Parameters received in the Job**  
![image](https://cloud.githubusercontent.com/assets/19808346/19505097/24e613ce-961c-11e6-86f9-d2a275acba8e.png)

If the job is triggered by the creation of the Pull request then the parameters are not being passed to the Jenkins job.

![image](https://cloud.githubusercontent.com/assets/19808346/19505227/63d82378-961d-11e6-868c-74a1380d45ad.png)

I am attempting to get Jenkins to comment on the Pull Request if the build fails or if the merge causes conflicts but without the PR_ID or PR_URL it makes it difficult.

**Comment by KyleLNicholls** [comment]
These parameters all work for me with PR_OPENED. Do you have the latest plugin build from the marketplace?

**Comment by edwardtew** [comment]
I have Atlassian Bitbucket v4.8.5, and I updated to the 2.6.0 from the market place.
![image](https://cloud.githubusercontent.com/assets/19808346/19536669/6ad9f944-96a9-11e6-9e1e-e24777ee4762.png)

I had a look at the code and (disclaimer: I'm not a java developer) the triggerFromPR appears to be the main operation with the variants for the differing trigger types.

I will try again with the Atlassian SDK and a local bitbucket instance to see if I can re-produce the issue with debugging. 

Do you have any advice about turning on extra logging information in the SDK?

**Comment by edwardtew** [comment]
It does seem to work when I OPEN, DECLINE or RE-OPEN a Pull request when I run the plugin on my windows desktop in the Atlassian SDK 
I'm using a Linux host for the production server if that could make a difference.

What would I need to add to the BitBucket properties file to enable logging for just your addon?

**Comment by edwardtew** [comment]
I'm not sure what fixed it but it is working now.
