### ISSUE TITLE
Error with # in branch name

### ISSUE THREAD

**Issue by skyline-gleb** [KyleLNicholls/parameterized-builds#45]
When branch have `#` in name, after click on "Build In Jenkins" nothing happens. In browser console see error on get hash by branch name, because GET request snip all after #.
![image-2016-10-18-16-36-09-840_2](https://cloud.githubusercontent.com/assets/4970194/19546637/a5a84e06-96bb-11e6-9056-3f5b5691bd03.png)
I use variable `$COMMIT` in build parameters.

**Comment by KyleLNicholls** [comment]
Fixed in v2.6.1
