### ISSUE TITLE
Trigger pull-request build paramter $PROJECT

### ISSUE THREAD

**Issue by barre80** [KyleLNicholls/parameterized-builds#47]
When using the $PROJECT paramter i get project name instead of project key as stated in documentation.

**Comment by KyleLNicholls** [comment]
Probably shouldn't have added this parameter to begin with. It's not useful. Jobs are specified at the repository level which means you can hard code the project name/key if you want.

**Comment by barre80** [comment]
Yes it possibile and I have don this as a workaround, but it is usefull if you want to make a template for multiple repos...
