### ISSUE TITLE
Access Keys page overridden by Jenkins Settings for repos beginning with "jenkins"

### ISSUE THREAD

**Issue by a-hacker** [KyleLNicholls/parameterized-builds#48]
Navigated to the Access Keys tab under a Repository's settings will instead load the global Jenkins settings if the name of the repo starts with jenkins. This issue presented itself on Bitbucket version 4.8.5 and parameterized builds version 4.6.0. However, the issue can be replicated on Bitbucket version 4.11.1 and the latest released version of this plugin (4.6.1).

I believe this issue stems from line 154 of the atlassian-plugin.xml. The regex provided captures the access key's url and loads the Jenkins Settings instead. I am not certain of this yet.

**Comment by KyleLNicholls** [comment]
fixed in 2.6.2
