### ISSUE TITLE
Invalid password/token for user: jbuilder

### ISSUE THREAD

**Issue by netropic** [KyleLNicholls/parameterized-builds#5]
When I try to trigger a build from the branch list i get a 401 error: "invalid password/token for user: jbuilder" and no build is triggered.

I've tried using no token, and using the jenkins api token for user 'jbuilder'. Same error in both cases.

What am I doing wrong?

**Comment by netropic** [comment]
Perhaps this is happening because my Jenkins requires authentication to hit the job/NAME/build REST URI? 

Perhaps the plugin should have a switch to allow use of https://wiki.jenkins-ci.org/display/JENKINS/Build+Token+Root+Plugin.

**Comment by KyleLNicholls** [comment]
I had this problem originally, I didn't know there was a plugin/workaround for it.
I'll take a look. Hopefully it won't be too difficult to implement.

**Comment by KyleLNicholls** [comment]
Made the changes, testing now. I'll have an update out Monday.

**Comment by netropic** [comment]
You the man!

**Comment by KyleLNicholls** [comment]
Pushed version 1.3.0 (for stash) and 2.2.0 (for bitbucket server) to the martketplace

**Comment by netropic** [comment]
Tested and confirmed to be working. Note that if you configure a token in the pop-up dialog from the repository branches page in Stash, the token in the global Jenkins Settings must be empty.
