### ISSUE TITLE
Provide $USER in addition to $PRAUTHOR 

### ISSUE THREAD

**Issue by amirhadar** [KyleLNicholls/parameterized-builds#50]
In case of PR trigger, sometimes there is a need to send a direct email to the Author of the PR. The provided PRAUTHOR does not provide a way to get the user information. 
By provideding $USER which is the login user of the PR author, the jenkins can send results email directly to the author.

BR
Amir Hadar

**Comment by edwardtew** [comment]
As the PR was created to review and check the changes that have been made it seems like it is the ideal place to track any problems with the code. 

If you think of jenkins as just another reviewer then it makes sense for the response to any build jobs to be sent to the PR. 

If jenkins sends an email to the PR author then the audit trail for subsequent changes spans three systems (BB , Jenkins, email) and is difficult to follow.

If you add a jenkins reviewer to the PR then you get the email notification all the same but so does everyone else on the review so it shares the workload if there is additional changes to be made.

**Comment by amirhadar** [comment]
Our BitBucket server does not send notifications on Build pass/failed for a PR to the reviewers and owner.

I cannot add jenkins as a real reviewer because jenkins does not have an Active Directory user.

If this add-on will provide ability to pass to jenkins all PR information including 
Author
Reviewers
It will ease up the integration.

**Comment by edwardtew** [comment]
You can add a local internal directory to BB for users that are not AD managed and then adding a comment to the Pull Request is just a simple REST API call
`curl -XPOST -s -u jenkins:password -H 'Content-Type: application/json' http://bitbucket/rest/api/1.0/projects/SW/repos/code/pull-requests/2418/comments -d '{"text": "CI Build FAILED. http://jenkins/job/ci-PR-Builder/1200/"}'`

Surely your BB server sends notifications when someone comments on the PR ?

**Comment by KyleLNicholls** [comment]
We could also probably do some clever json expansion  in the build parameters so you could have access to the whole pullRequest json object. For example:

Build Parameters:
> destionBranch=$($PULLREQUEST.fromRef.id)
> authorEmail=$($PULLREQUEST.author.user.emailAddress)

It would cut back on a lot of the PR variables (there are already 6). Not sure how feasible this would be to code though.

Examples of the PR json object can be found here: https://developer.atlassian.com/static/rest/bitbucket-server/4.11.1/bitbucket-rest.html

**Comment by edwardtew** [comment]
It seems to me that if the PR job on Jenkins needs to know more about the PR than the parameters provided it can ask BB for the JSON itself.

**Comment by KyleLNicholls** [comment]
I'm not disagreeing with you, I regret adding the existing PR variables. More of just looking for a way to remove the existing 6 PR variables (excluding PR ID) without removing features that people might be using.

**Comment by amirhadar** [comment]
I agree I can get all the info from the PRID
