### ISSUE TITLE
Suggestion: Manual Trigger Permissions

### ISSUE THREAD

**Issue by amirhadar** [KyleLNicholls/parameterized-builds#51]
Using manual trigger we can run several jobs by selecting one in the dropdown box.
This is a great feature which is very helpfull.

One of the jobs I would like to offer the development team is "Release", but only the project integrator is permitted to issue a release. I would like to avoid developers triggering this job by mistake. 

Adding permissions to a manual trigger will allow us to specify who can do what.

**Comment by a-hacker** [comment]
@amirhadar @KyleLNicholls , I am looking into potentially adding this feature. The feature would end up looking something like this... 
![manual_trigger_permissions](https://cloud.githubusercontent.com/assets/3665996/23489989/9eede876-fec3-11e6-9df2-266cad25bd6f.png)

The repository level permissions will be the required access level in the dropdown but any project or global level permissions will be inherited (i.e. if a user is given write access on the project then they will be able to run any job that requires write access to the repo). Will this satisfy your use case or if there any modifications you would like to see to this approach?

**Comment by KyleLNicholls** [comment]
Released in v3.1.0
thanks @a-hacker
