### ISSUE TITLE
Incorrect $PROJECT parameter when a job triggered automatically

### ISSUE THREAD

**Issue by xtimon** [KyleLNicholls/parameterized-builds#52]
When a job triggered automatically by a pull request the parameter $PROJECT returns the project name, not the project key.
But when i trigger a job by the button the parameter $PROJECT returns correct project key.

**Comment by a-hacker** [comment]
+1 I experienced the same issue.

**Comment by KyleLNicholls** [comment]
What is the expected behavior you want, the project key or project name? I didn't write this feature and I just hard code repo info into the hook settings when I need to.

**Comment by KyleLNicholls** [comment]
resolved in v2.6.4
