### ISSUE TITLE
Update 2.6.4 bug

### ISSUE THREAD

**Issue by ntende** [KyleLNicholls/parameterized-builds#54]
After the applying this update, the Choice parameter do not display and the Boolean parameter choice box  does not show up!. Seems the bug was introduced in 2.6.3.

**Comment by KyleLNicholls** [comment]
Thanks, fixed in 2.6.5

**Comment by ntende** [comment]
A little bug..when the a boolean parameter is defined..the Start Build  Job gets disabled. Current workaround using choice parameters.

**Comment by a-hacker** [comment]
I've created Issue #59 for this.
