### ISSUE TITLE
PR triggering Jenkins build despite hook being disabled

### ISSUE THREAD

**Issue by lucymhdavies** [KyleLNicholls/parameterized-builds#56]
This one's kinda weird.

Hook config:

<img width="839" alt="screen shot 2017-02-02 at 14 36 09" src="https://cloud.githubusercontent.com/assets/1116529/22553624/5bf73f82-e955-11e6-95fa-d2713fbb12e0.png">

But I also have the hook disabled.

And yet, BitBucket triggered a Jenkins job when I opened a PR.

None of the following triggers have the problem:
ref created, push event, manual, ref deleted

All of the following triggers have the problem:
pr opened, pr merged, pr declined

This is with BitBucket server version 4.6.1, and plugin version 2.5.2

Of course, simple workaround is to just disable those triggers.

**Comment by KyleLNicholls** [comment]
The fix will go out in the next release, thanks
