### ISSUE TITLE
More granularity in PR types or actions

### ISSUE THREAD

**Issue by gepandz** [KyleLNicholls/parameterized-builds#6]
Hi! I'm finding lots of value in this plugin. I notice that you have the ability to trigger on PR actions, but only (each of) open, reopen, and rescope, but not approve or merge events. Is there a way to give us some more granularity on these actions?

Specifically, we use PRs to trigger code-reviews within our team, so we'd prefer if we only trigger the hook on Merge of the PR, rather than deploying the code the minute the PR is created. Is that possible? We don't allow updating the mainline branches except through PRs, so triggering on a push would not work in our workflow, though we're open to changing the workflow if there's a better way.

Thank you for your time on this! This is great work.

**Comment by KyleLNicholls** [comment]
I can look into this. If you don't mind me asking, do you use bitbucket server or stash?

**Comment by KyleLNicholls** [comment]
![image](https://cloud.githubusercontent.com/assets/5102232/12421741/a69442a0-be91-11e5-9903-a946cd0047d9.png)
Is that enough granularity or are you looking for more options?

**Comment by gepandz** [comment]
We use BitBucket Server.

That would be great. Thanks for the quick turnaround. :+1:

**Comment by KyleLNicholls** [comment]
Pushed to marketplace for bitbucket server and stash
