### ISSUE TITLE
Bitbucket automerging - PR hooks not triggering

### ISSUE THREAD

**Issue by shawnburrington** [KyleLNicholls/parameterized-builds#62]
We enabled the Bitbucket automerge feature which automatically merges to multiple downstream branches after a PR merge occurs on a desired branch. Unfortunately the plugin only triggers off of the PR to the initial destination branch, rather than the (presumed) PR's to all subsequent branches. 

The thought right now is that Bitbucket isn't actually submitting a pull request to these subsequent branches, but instead submitting some other type of trigger "under-the-hood"... 

Bitbucket automerge documentation: https://confluence.atlassian.com/bitbucketserver0411/automatic-branch-merging-861180551.html?utm_campaign=in-app-help&utm_medium=in-app-help&utm_source=stash

**Comment by a-hacker** [comment]
I've dug into this issue a bit. Unfortunately, there's no simple solution here because of the way that Bitbucket handles an automatic merge event. I believe it would be possible to support handling an automatic merge as a PR Merged Event but the PR specific variables would be unavailable.

**Comment by KyleLNicholls** [comment]
This has been released in 2.6.7
Thanks @a-hacker !

**Comment by shawnburrington** [comment]
Thanks guys, awesome!
