### ISSUE TITLE
Plugin doesn't work against CSRF

### ISSUE THREAD

**Issue by thegreenbear** [KyleLNicholls/parameterized-builds#67]
Unless I'm mistaken, the plugin won't work against a jenkins server that has CSRF protection on.
The pluging would need to retrieve a crumb before doing any POST requests to the server as described in https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API#RemoteaccessAPI-CSRFProtection

Is there any chance this could be implemented?

Thanks!
Awsome plugin by the way :-)

**Comment by KyleLNicholls** [comment]
released in v2.6.8
thanks @a-hacker

**Comment by thegreenbear** [comment]
Awsome! Thanks a lot :-) Great plugin by the way.
