### ISSUE TITLE
Configure multiple Jenkins servers

### ISSUE THREAD

**Issue by bogdanhruban** [KyleLNicholls/parameterized-builds#7]
Hi,

Is there a way to use this plugin on one Bitbucket installation with multiple Jenkins servers linked to it?
Currently this provides in the configuration settings an option to login on one Jenkins instance only.

Any advice how to use the plugin with this setup is really much appreciated. 

Thanks,
Bogdan

**Comment by KyleLNicholls** [comment]
Unfortunately not at this time. It's not really on my todo list either (I've got a day job that keeps me busy now).
I tried to implement it at one point but ran into some stash limitations with soy templates. I accept pull requests if anyone wants to add this feature.

**Comment by KyleLNicholls** [comment]
I'm working on this now

**Comment by KyleLNicholls** [comment]
release v2.5.0 to the marketplace
