### ISSUE TITLE
Problems with latest CSRF update together with Build Token-setting

### ISSUE THREAD

**Issue by petterm** [KyleLNicholls/parameterized-builds#71]
Im running a setup with Bitbucket server together with Jenkins and since updating to the last version of this plugin I have started seeing builds triggered twice, first from the new CSRF-call and then for the regular call. It seems the CSRF-call for some reason triggers a regular job instead of just fetching a security token, and the extra path from the CSRF-call also leaks into the build parameters.

**Setup:**
Atlassian Bitbucket v4.10.1
Parameterized Builds for Jenkins v2.6.8
Jenkins v2.32.3 (with CSRF enabled)
Build Authorization Token Root Plugin v1.4

**Comment by thegreenbear** [comment]
Also observed this behavior.

**Comment by KyleLNicholls** [comment]
fixed in c3.1.1
