### ISSUE TITLE
Choice parameter on Bitbucket Pull request view

### ISSUE THREAD

**Issue by vliloia** [KyleLNicholls/parameterized-builds#72]
Hi
Since we use the plugin with Bitbucket 4 we're facing a problem with the choice parameter when navigating via the Pull-Request view (Pull requests -> select branch -> ... -> Build in Jenkins). In that case the parameter is not visible. Surprisingly when navigating via the branch view (Branch -> ... -> Build in Jenkins) it works like usual. Any idea on why the plugin behaves divergent?

Atlassian Bitbucket v4.14.5
Parameterized Builds for Jenkins v2.6.8
Jenkins v2.19.3

**Comment by a-hacker** [comment]
It looks like this is the same issue as issue #54 but the fix from that only got applied to the branch and source views but not to the pull requests page. I'll get that fixed ASAP.

**Comment by KyleLNicholls** [comment]
released in v2.6.9
