### ISSUE TITLE
Add support for onTag trigger

### ISSUE THREAD

**Issue by otbe** [KyleLNicholls/parameterized-builds#8]
Hi

it would be very nice to have an ```onTag``` trigger for compiling artifacts on a per tag base.

What do you think about it?

**Comment by KyleLNicholls** [comment]
Makes sense. Running into option overload though, I need to think about redesigning that flow.
What version of stash/bitbucket do you use?

**Comment by otbe** [comment]
We are using Bitbucket v4.4.1 right now.
I think its fine to add one more options, because the number of people which configure this hook is limited, but its up to you :)

Thanks!

**Comment by KyleLNicholls** [comment]
Yeah there aren't as many options in that section as I thought. Unfortunately I'll be on PTO until June 6th. I probably won't get around to it until after then. Thanks for the suggestion though.
P.S. I do accept pull requests ;)

**Comment by KyleLNicholls** [comment]
Just to clarify, you want an on tag created trigger? ie trigger a build when a tag is pushed to the repo

**Comment by otbe** [comment]
Yeah thats what Im looking for :)

**Comment by KyleLNicholls** [comment]
v2.4.0 released to the marketplace

**Comment by otbe** [comment]
Great work. Thanks!
