### ISSUE TITLE
The plugin (3.1.0) breaks the Pull Request view on Bitbucket server v5.1.3

### ISSUE THREAD

**Issue by swingerman** [KyleLNicholls/parameterized-builds#81]
If the plugin is enabled on Bitbucket server v5.1.3 then the Pull Request view is empty.

The JS console shows a 404 error on getJobs.js request.

I pinpointed this by disabling all plugins and reenabled one by one. The PR view was broken when this plugin was enabled.

**Comment by Gabitchov** [comment]
Hello,

I installed the plugin today and I had this bug. This is blocking use of this one.

Regards,

Gabriel

Configuration:
   - Bitbucket 5.1.2

**Comment by a-hacker** [comment]
We are aware of the issue and PR #79 has been submitted to address this. It should be fixed soon.

**Comment by KyleLNicholls** [comment]
Sorry, I've been out of town
fixed in v3.1.1
