### ISSUE TITLE
Git Push error if current repository not set up for jenkins

### ISSUE THREAD

**Issue by swingerman** [KyleLNicholls/parameterized-builds#85]
Hello,

We see error messages in console while pushing to a repository that is not integrated with your plugin (3.2).
remote: [18:28:18] [ERROR] [Unhandled Expetion. Please contact info@develop-and-consult.de] Commit '0000000000000000000000000000000000000000' does not exist in repository

It doesn't stop  us to work but a bit annoying.

Please have a look.

**Comment by a-hacker** [comment]
@swingerman, I can't seem to replicate this issue and based on the error you posted, I suspect that this isn't an issue inherent to this plugin but an issue caused by a different plugin. It is possible that another plugin does not play nice with ours. Could I ask what other plugins you have installed?

**Comment by swingerman** [comment]
Here is the list of plugins we use:

- The Tag Maker
- Bitbucket Server Webhook to Jenkins
- Pull Request Leaderboard
- pull-request-notifier-for-bitbucket
- Bitbucket Look and Feel Plugin
- Bitbucket Server - Auto Unapprove Pull Requests
- branchDetails
- Commit Graph
- Jira Hooks for Stash
- Slack notifications for pull request and push activities
- Smart Commits for Bitbucket

I see the error only on a specific repository though.

**Comment by a-hacker** [comment]
Thanks for the list. I'll try to look into what the issue is but since this seems to be a compatibility problem with another plugin, I'll be considering it a low priority issue.

**Comment by a-hacker** [comment]
@swingerman I know it has been awhile but I haven't been able to reproduce the issue at all. If you can provide a reproducible example of this issue, then I will look again.
