### ISSUE TITLE
Filter PR Opened, Merged, and Declined based on Branch

### ISSUE THREAD

**Issue by belldevelopers** [KyleLNicholls/parameterized-builds#86]
Between this plugin and the "Pull Request Notifier for Bitbucket Server" I can't quite accomplish what I want to do. I want to:
1. Trigger a Jenkins task on a PR Merge
2. Filter on the PULL_REQUEST_[TO,FORM]_BRANCH
3. Authenticate using the users jenkins API Token

Your plugin only provided the capability to do 1 and 3. Filtering on branch or tag is not available for PR Triggers. I would like to have the ability to filter on the TO_BRANCH, and possibly the FROM_BRANCH, in a PR Trigger.

(Only providing this for example purpose) The "Pull Request Notifier for Bitbucket Server" plugin provides the capability to filter on many variables. (https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket)

Is there any chance this can be added as a new feature?

**Comment by a-hacker** [comment]
This issue clones #38 for the most part. You do add the FROM_BRANCH bit that wasn't asked for in that issue so I'll keep it in mind. 

There is a workaround if you have a branch you do not push directly to but want to trigger a job on PR merges. What you can do if specify a push trigger on the job and use the branch filter to match the given branch. A PR merge to that branch should cause a push event on it so the jenkins job will be triggered. I'm not 100% on this but I believe it will work.

**Comment by belldevelopers** [comment]
For anyone that needs to know. Yes, a PR Merge does cause a Push Event and a jenkins job will be triggered.
