### ISSUE TITLE
PR Triggers not working in Bitbucket 5.0.1

### ISSUE THREAD

**Issue by belldevelopers** [KyleLNicholls/parameterized-builds#89]
I am not sure if I have something configured wrong but I have been opening, declining and re-opening a pull-request for testing and nothing seems to be happening.

Bitbucket 5.0.1
 -> Enable debug logging
parameterized-builds 3.1.1
 -> Ref Type: branch
 -> Triggers: PR OPENDED, PR DECLINED
Jenkins 2.19.1

Bitbucket logs shows several:
[AtlassianEvent::thread-xx] events including PullRequestActivityNotification, PullRequestReopenedNotification, RemoteEvent StashPullRequestRemoteEvent
and something like:
RemoteEventListener Batch size not exceeded for  com.atlassian.stash.plugin.remote.event.StashPullRequestReopenedRemoteEvent
(The logs are on a standalone system that I can pull the logs off of. This is the bested I can do.)

It doesn't look like the hook is even attempting to trigger anything on a PR*. Any help would be great!

**Comment by a-hacker** [comment]
It may have something to do with your Jenkins settings. I'd set the MANUAL trigger and try building using the `Build in Jenkins` button. If there is an error, a flash message will pop up with the details of what is wrong.

**Comment by belldevelopers** [comment]
Running it manually with the button worked fine (Jenkins kicked off a build).
I know the tag create works as well (I accidently left the trigger enabled when pushing 1000+ tags, that was fun!)
I have gotten Push events to work previously, but I have yet to see a PR event trigger anything yet. I am not sure why. 

For all of the above, it doesn't seem to have any logging from the plugin. I'm not sure if it's a Bitbucket version issue with Listeners or not.

**Comment by a-hacker** [comment]
That is quite odd. Most of my testing has been on bitbucket versions 5.0.2 and 5.1.0. I'll see if 5.0.1 has issues although I find that unlikely.

Could you give me a list of the other plugins you have installed on your bitbucket server? It could be that another plugin is somehow interfering with or changing the events that cause the triggers.

**Comment by belldevelopers** [comment]
I was thinking the same thing. I can get a list tomorrow, but I have a feeling the only one that might be causing issues would be 'pull-request-notifier-for-bitbucket'. I will try disabling it and see if I can get the triggers working.

I am mainly using that plugin until I get the PR Triggers working and I can filter PR Triggers on to/from branches. :P

Thanks for all the help!

**Comment by belldevelopers** [comment]
Plugins we currently have active:
All Pull Requests
Bitbucket Server Archive Plugin
Bitbucket Server Auto Unapprove Plugin
Bitbucket Server Look and Feel Plugin
Bitbucket Server Protect Unmerged Hook
Commit Graph
Commit Policy Plugin for Bitbucket
External Hooks
Fork List
Parameterized Builds for Jenkins
PR Harmony
Pull Request Notifier for Bitbucket
Repository Mirror Plugin for Bitbucket Server
SSH Support for Pull Request
Tag Details And Git Notes

I disabled all plugins and retested, still not luck triggering PR events. I was able to prove that a PR Merge event triggered a Push Event. So that gets me part of the way there.

**Comment by sberg413** [comment]
Was there ever any resolution on this. I'm having the exact same issue - the "Build in Jenkins" manual build works (and populates the correct params). Creating a PR does nothing for me. Is this a known bug?

**Comment by a-hacker** [comment]
@sberg413, are you able to trigger a build from a push event, ref created, or ref deleted event? If so, it is possible that you have the same issue as @belldevelopers and it would be helpful if you could provide a list of all installed plugins like @belldevelopers did. I've been unable to replicate the issue so far but more data could help me solve the issue.

If you can't trigger from any of  push event, ref created, or ref deleted events then you likely have a different issue in which case I'd ask that you please open a new issue with any info that would allow me to recreate your bug.

**Comment by bhoppeadoy** [comment]
I'm having similar issues with PRs.  I'm running

BitBucket Server v5.4.1
Parameterized-builds 3.2.0
Jenkins 2.93

I have multibranch pipeline configured with BitBucket branch source. I have it configured to discover all branches and discover pull requests from origin (current PR revision). 

For REF_CREATED, REF_DELETED, and PUSH_EVENT the trigger works fine. For PR_OPENED and PR_DELETED, the trigger doesn't work properly. When I open a pull request instead of creating a new build under the Pull Requests tab for the job in jenkins, it triggers a build on the feature branch. From jenkins if I click "Scan Multibranch Pipeline Now" then the new PR shows up under the Pull Requests tab. Same thing happens when deleting a pull request.

Shouldn't PR_OPENED and PR_DELETED setup to run a scan?

I see that from #93, you have a PR trigger a build. This shouldn't work because the PR build doesn't exist yet when the PR is first opened. A scan has to happen for the multibranch pipeline to see the pull request and create the build for it. A PR_OPENED and PR_DELETED are pretty much the same thing as REF_CREATED and REF_DELETED.

**Comment by a-hacker** [comment]
@bhoppeadoy, your issue is unrelated to this one. Multibranch pipeline support was implemented in 3.2.0 and this issue relates to an earlier version. I see you opened a seperate issue as well so I will respond to it there.

**Comment by ellechir** [comment]
Did you find a fix/resolution on this? I am also having a problem wherein Jenkin build is not triggered when PR is created. By the way, I am using forking workflow. If I manually trigger the jenkin build, it will work though. Do you have any idea why this is happening?

Thank you very much for your help!

**Comment by a-hacker** [comment]
Because this issue was opened against Bitbucket Server 5 and we are only supporting Bitbucket Server 6 now, I am closing this issue. If the problem persists for current Bitbucket Server versions, please create a new ticket.
