### ISSUE TITLE
Jenkins user token not used

### ISSUE THREAD

**Issue by uweschaefer** [KyleLNicholls/parameterized-builds#9]
When using a ParameterizedBuildHook, the field "Token" is described as "Trigger builds remotely (e.g., from scripts) or leave blank to use user API token".

Unfortunately, the User API token is not used when the field is left blank.

Pulling the sources, it looks like 

ParameterizedBuildHook:61
```java
jenkins.triggerJob(job, query, null);
```

passes `null` where the userToken should be.

Context: What we're trying to do is trigger a job upon new branch creation. This job should use the current user and his Jenkins API Token to authenticate to Jenkins rather than having a shared secret Token.
Is this possible with the current version, or would that be feature request?

ps: we're ready to help.

**Comment by uweschaefer** [comment]
forgot to mention: Yes, the Token was entered via `Jenkins User Settings`

**Comment by KyleLNicholls** [comment]
thanks, I'll review it this afternoon

**Comment by KyleLNicholls** [comment]
I'll try to update the marketplace tonight once I finish issue #8

**Comment by uweschaefer** [comment]
thanks!
