### ISSUE TITLE
Performance Issue: Publishing webhooks on event threads

### ISSUE THREAD

**Issue by jeffsigmon** [KyleLNicholls/parameterized-builds#95]
It seems this plugin is publishing webhooks on event threads which can lead to performance problems. Please see [this issue](https://github.com/Eernie/bitbucket-webhooks-plugin/issues/54) for more information.

**Comment by jeffsigmon** [comment]
I've submitted PR #96 to address this issue.

**Comment by KyleLNicholls** [comment]
Thanks @jeffsigmon 
Released in v3.1.3
